import juice from '../../../../assets/images/lobby/juice.webp';
import depos from '../../../../assets/images/lobby/invest_deposit.webp';
import shares from '../../../../assets/images/lobby/invest_shares.webp';
import book from '../../../../assets/images/lobby/invest_book.webp';
import cycle from '../../../../assets/images/lobby/invest_cycle.webp';
import course from '../../../../assets/images/lobby/invest_course.webp';
import obligation from '../../../../assets/images/lobby/invest_obligation.webp';
import ticket from '../../../../assets/images/lobby/invest_ticket.webp';
import sport from '../../../../assets/images/lobby/invest_sport.webp';
import { SCREENS } from '../../../../constants/screens';

export const CELL_CONTENT = {
  'w1_bonus_idea_award': {
    title: "Премия за идею",
    income: 200,
    cost: null,
    name: "w1_bonus_idea_award",
    id: "w1_bonus_idea_award",
    type: "bonus",
    week: 1,
    description: "На дейлике ты предложил решение для горящей задачи.\nКоманда закрыла её быстрее, а тебе — премия.\nВТБ предлагает высокий доход прямо со старта карьеры",
  },
  'w1_minigame_coin_runner': {
    title: "Коин-раннер",
    screen: SCREENS.GAMERUNNER,
    cost: null,
    name: "w1_minigame_coin_runner",
    id: "w1_minigame_coin_runner",
    type: "minigame",
    week: 1,
    description: "Беги, лови коины, уворачивайся от лишних трат.\nПокажи класс за 90 секунд",
  },
  'w1_luck_notification': {
    title: "Уведомление",
    notification: {
      luck: '+10000 руб. от родителей:\n«Купи себе кроссовки, которые понравились!»',
      badluck: 'Списание 499 руб.\nЕжемесячная подписка «Слушаем и обсуждаем»'
    },
    income: 700,
    cost: -350,
    name: "w1_luck_notification",
    id: "w1_luck_notification",
    type: "luck",
    week: 1,
    luckDescription: "Тебе пришло новое уведомление. Удача сегодня на твоей стороне",
    badluckDescription: "Тебе пришло новое уведомление. Пупупу… ты забыл отключить автопродление",
  },
  'w1_quiz_rich_or_broke': {
    title: "Разбогател или прогорел?",
    income: 300,
    cost: null,
    name: "w1_quiz_rich_or_broke",
    id: "w1_quiz_rich_or_broke",
    type: "quiz",
    week: 1,
    isSmallAnswer: true,
    question: "Есть предложение, которое выглядит суперзаманчиво.\nНо ты же понимаешь… не всё золото, что блестит. Сделаешь правильный выбор — коины твои.\n\nДруг зовёт вложить всё в тему, которая «точно стрельнет».\nТвои действия?",
    answersInfo: [
      "А. Вкладывать всю сумму в один актив — большой риск. Если темка не стрельнет, то потеряешь все деньги сразу",
      "B. Рискуй, но по чуть-чуть. Даже если не стрельнет — не критично",
      "C. Инвестировать заёмные деньги опасно: если вложение не сработает, долг всё равно придётся возвращать, ещё и с процентами — анлак"
    ],
    answers: [
      "А. Вложу всё",
      "B. Вложу только то, что не страшно потерять",
      "C. Возьму кредит и вложу"
    ],
    correctAnswer: 2,
  },
  'w1_investment_vtb_deposit': {
    modalImage: depos,
    imgStyle: {
      width: 301,
      height: 279,
      marginTop: 16,
      marginBottom: 40,
    },
    title: "Вклад ВТБ",
    income: 150,
    incomeNextWeeks: 280,
    cost: -400,
    name: "w1_investment_vtb_deposit",
    id: "w1_investment_vtb_deposit",
    type: "investment",
    week: 1,
    description: "Деньги тоже должны работать.\nОткрой вклад и начни получать стабильный доход каждую неделю",
  },
  'w1_investment_financial_literacy_course': {
    modalImage: course,
    imgStyle: {
      width: 250,
      height: 223,
      marginTop: 2,
      marginLeft: 20,
      marginBottom: 35,
    },
    title: "Курс\nфинграмотности",
    isPercent: true,
    percent: 8,
    income: "+8%",
    incomePercentNextWeeks: 8,
    cost: -400,
    name: "w1_investment_financial_literacy_course",
    id: "w1_investment_financial_literacy_course",
    type: "investment",
    week: 1,
    description: <span>
      В ВТБ для твоей постоянной прокачки доступны курсы, тренинги и онлайн-библиотеки МИФ и Альпина. Для стажёров — отдельная программа обучения банковскому делу. <a href="https://rabota.vtb.ru/internship/" target='_blank'>Подробности ищи на сайте</a>
    </span>
  },
  'w1_luck_fashion_shopping': {
    title: "Шопинг:\nмодный лук",
    income: 700,
    cost: -350,
    name: "w1_luck_fashion_shopping",
    id: "w1_luck_fashion_shopping",
    type: "luck",
    week: 1,
    luckDescription: "Сегодня было в планах купить новую одежду на осень. Плюс вайб!\nУ твоего любимого бренда как раз скидки",
    badluckDescription: "Сегодня было в планах купить новую одежду на осень.\nПупупу... дома ты обнаружил, что тебе продали фейк",
  },
  'w1_minigame_collect_capital': {
    title: "Собери капитал",
    screen: SCREENS.GAME2048,
    cost: null,
    name: "w1_minigame_collect_capital",
    id: "w1_minigame_collect_capital",
    type: "minigame",
    week: 1,
    description: "Объединяй одинаковые активы и дорасти капитал до цели",
  },
  'w1_bonus_initiative_bonus': {
    title: "Бонус за\nинициативу",
    income: 200,
    cost: null,
    name: "w1_bonus_initiative_bonus",
    id: "w1_bonus_initiative_bonus",
    type: "bonus",
    week: 1,
    description: "Ты заметил, что команда каждую неделю тратит кучу времени на создание презентаций и предложил идею, как это оптимизировать. Минус рутина и плюс бонус от начальства.\n\nПроявляем инициативу — одна из корпоративных ценностей ВТБ",
  },
  'w1_quiz_spare_money': {
    title: "Свободные\nденьги",
    income: 300,
    cost: null,
    name: "w1_quiz_spare_money",
    id: "w1_quiz_spare_money",
    type: "quiz",
    week: 1,
    question: "Все счета оплачены, зарплата ещё не закончилась. Редкий момент!\nЧто дальше?",
    answers: [
      "А. Пока просто полежат на карте",
      "B. Закину на накопительный счёт — пусть капают проценты",
      "C. Самое время заказать всё из корзины на маркетплейсе"
    ],
    answersInfo: [
      "А. Так деньги не работают, а просто лежат, пока ты думаешь, куда их потратить",
      "B. Даже небольшой процент лучше, чем хранить их без пользы",
      "C. Не поддавайся на импульсивные покупки, а думай наперёд!"
    ],
    correctAnswer: 2,
  },
  'w1_investment_scooter_subscription': {
    modalImage: cycle,
    imgStyle: {
      width: 291 * 1.04,
      height: 265 * 1.04,
      marginTop: 0,
      marginLeft: -10,
    },
    title: "Купил велосипед",
    income: 50,
    incomeNextWeeks: 80,
    cost: -200,
    name: "w1_investment_scooter_subscription",
    id: "w1_investment_scooter_subscription",
    type: "investment",
    week: 1,
    description: "Велосипед — чит-код против пробок. Конечно, это не моноколесо, зато экономишь время в час пик и успеваешь больше",
  },
  'w1_luck_autumn_season': {
    title: "Осенняя пора",
    income: 700,
    cost: -350,
    name: "w1_luck_autumn_season",
    id: "w1_luck_autumn_season",
    type: "luck",
    week: 1,
    luckDescription: "Похолодало, и пошёл дождь — а через час встреча с клиентом. Такси удалось поймать сразу, доехал сухим и вовремя. Сюдаааа\n\nРабочие поездки в ВТБ не проблема — компенсируют такси, чтобы ты спокойно добирался до нужных задач",
    badluckDescription: "Похолодало, и пошёл дождь — а через час встреча с клиентом. Кажется, зонтик остался дома и придётся вызывать такси. Минус вайб(\n\nА рабочие поездки в ВТБ не проблема — компенсируют такси, чтобы ты спокойно добирался до нужных задач",
  },
  'w1_investment_vtb_shares': {
    modalImage: shares,
    imgStyle: {
      width: 243,
      height: 237,
      marginTop: 11,
      marginLeft: 20,
      marginBottom: 74,
    },
    title: "Акции ВТБ",
    income: 150,
    incomeNextWeeks: 280,
    cost: -400,
    name: "w1_investment_vtb_shares",
    id: "w1_investment_vtb_shares",
    type: "investment",
    week: 1,
    description: "Инвестируй в компании, в которые веришь. Если они растут, растут и твои возможности",
  },
  'w1_minigame_match3': {
    screen: SCREENS.GAMEMATCH3,
    title: "Три в ряд",
    cost: null,
    name: "w1_minigame_match3",
    id: "w1_minigame_match3",
    type: "minigame",
    week: 1,
    description: "Комбинируй одинаковые активы, запускай комбо и заработай как можно больше коинов",
  },
  'w1_bonus_vacation': {
    title: "В отпуске,\nпью джус",
    modalImage: juice,
    imgStyle: {
      position: 'absolute',
      left: '50%',
      top: '5%',
      transform: 'translateX(-50%)',
      width: 198,
      overflow: 'visible',
      height: 337,
    },
    income: 200,
    cost: null,
    name: "w1_bonus_vacation",
    id: "w1_bonus_vacation",
    type: "bonus",
    week: 1,
    description: "А вот и отпускные — лови +3 дня отдыха от ВТБ.\n\nМного зарабатывать не равно мало отдыхать!",
  },
  'w1_luck_bank_push': {
    notification: {
      luck: "Начислен кэшбэк...",
      luckHeight: 40,
      badluckHeight: 90,
      badluck: "Списана оплата за подписку на киносервис. Помнишь, как брал её за 1₽ на пробный период?\nКак всегда не вовремя"
    },
    title: "Пуш от банка",
    income: 700,
    cost: -350,
    name: "w1_luck_bank_push",
    id: "w1_luck_bank_push",
    type: "luck",
    week: 1,
    badluckAdditional: "А для сотрудников ВТБ действуют бонусы от банка и программы лояльности, чтобы кэшбэк был приятнее, а оплата услуг — всегда вовремя",
    luckAdditional: "Как неожиданно и прияяятно",
    badluckDescription: "Тебе пришло новое уведомление",
    luckDescription: "Тебе пришло новое уведомление",
  },
  'w1_investment_finance_conference_ticket': {
    modalImage: ticket,
    imgStyle: {
      width: 243,
      height: 195,
      marginTop: 18,
      marginLeft: 21,
      marginBottom: 53,
    },
    isPercent: true,
    percent: 8,
    title: "Билет\nна конференцию\nфинансистов",
    income: "+8%",
    incomePercentNextWeeks: 8,
    cost: -400,
    name: "w1_investment_finance_conference_ticket",
    id: "w1_investment_finance_conference_ticket",
    type: "investment",
    week: 1,
    description: <span>Хороший нетворкинг решает.{'\n\n'}А ВТБ регулярно проводит полезные мероприятия для твоего развития. Ищи их на <a href="https://rabota.vtb.ru/internship/" target="_blank">карьерном сайте ВТБ</a></span>,
  },
  'w1_quiz_70_discount': {
    title: "Скидка 70%!",
    income: 300,
    cost: null,
    name: "w1_quiz_70_discount",
    id: "w1_quiz_70_discount",
    type: "quiz",
    week: 1,
    question: "Твоя модель телефона устарела, хочется новый... Скроллишь ленту и попадается баннер: «Новый смартфон в рассрочку без первого взноса». Как поступишь?",
    answers: [
      "А. Беру не раздумывая",
      "B. Изучу условия и посчитаю переплату",
      "C. Возьму сразу два — второй потом пригодится"
    ],
    answersInfo: [
      "А. Хорошо звучит, но не факт, что выгодно",
      "B. Грамотные действия и отсутствие переплаты",
      "C. Запасные деньги звучит лучше, чем запасной телефон, не думаешь?"
    ],
    correctAnswer: 2,
  },
  'w1_investment_gym_membership': {
    modalImage: sport,
    imgStyle: {
      width: 282,
      height: 206,
      marginTop: 13,
      marginLeft: 0,
      marginBottom: 58,
    },
    title: "Абонемент\nв спортзал",
    income: 50,
    incomeNextWeeks: 80,
    cost: -200,
    name: "w1_investment_gym_membership",
    id: "w1_investment_gym_membership",
    type: "investment",
    week: 1,
    description: "Забота о здоровье — тоже инвестиция: энергии больше, стресса меньше.\n\nВТБ порадует скидками на спортзалы, а ещё у него есть свои спортивные сообщества",
  },
  'w1_minigame_catch_items': {
    screen: SCREENS.GAMECATCH,
    title: "Лови актив",
    cost: null,
    name: "w1_minigame_catch_items",
    id: "w1_minigame_catch_items",
    type: "minigame",
    week: 1,
    description: "Это что, денежный дождь?\nСобирай полезные активы и уворачивайся от ненужных трат",
  },
  'w1_luck_past_returns': {
    title: "Всплыло\nиз прошлого",
    income: 700,
    cost: -350,
    name: "w1_luck_past_returns",
    id: "w1_luck_past_returns",
    type: "luck",
    week: 1,
    luckDescription: "День начинается не с кофе… а с приятных новостей! Пришла компенсация мобильной связи\nот ВТБ",
    badluckDescription: "День начинается не с кофе… а с забытой платёжки по ЖКХ. Сегодня последний день, срочно нужно оплатить!",
  },
  'w1_investment_bonds': {
    modalImage: obligation,
    imgStyle: {
      width: 300,
      height: 300,
      marginTop: -12,
      marginLeft: -10,
      marginBottom: 56,
    },
    title: "Облигации",
    income: 150,
    incomeNextWeeks: 280,
    cost: -400,
    name: "w1_investment_bonds",
    id: "w1_investment_bonds",
    type: "investment",
    week: 1,
    description: "Не хайп, зато надёжно. Хороший способ постепенно увеличивать капитал",
  },
  'w1_bonus_good_vibes': {
    title: "Плюс вайб",
    income: 200,
    cost: null,
    name: "w1_bonus_good_vibes",
    id: "w1_bonus_good_vibes",
    type: "bonus",
    week: 1,
    description: "Собрал дашборд, который наконец-то показывает вообще всё. Команда в восторге, а тебе начислили бонус",
  },
  'w1_investment_investing_book': {
    modalImage: book,
    imgStyle: {
      width: 197,
      height: 153,
      marginTop: 11,
      marginLeft: 45,
      marginBottom: 0,
    },
    title: "Книга\nоб инвестициях",
    isPercent: true,
    percent: 8,
    income: "+8%",
    incomePercentNextWeeks: 8,
    cost: -400,
    name: "w1_investment_investing_book",
    id: "w1_investment_investing_book",
    type: "investment",
    week: 1,
    description: "Вместо вечернего скролла ленты с мемами — пара глав. Теперь принимать финансовые решения станет проще\n\nОсобенно проще принимать решения в сильной экспертной команде единомышленников в ВТБ",
  },
  'w1_minigame_financial_flow': {
    screen: SCREENS.GAMECROSS,
    title: "Финансовый\nпоток",
    cost: null,
    name: "w1_minigame_financial_flow",
    id: "w1_minigame_financial_flow",
    type: "minigame",
    week: 1,
    description: "Пересекай поток трат и рисков и доберись до финала",
  },
};