export const SCREENS = {
    INTROREG: 'INTROREG',
    REG: 'REG',
    WAITING: 'WAITING',
    INTRO_RULES: 'INTRO_RULES',
    PROFILE: 'PROFILE',
    LOBBY: 'LOBBY',
    STORE: 'STORE',
    AWARDS: 'AWARDS',
    RULES: 'RULES',
    GAMES: 'GAMES',
    GAMEDOODLE: 'GAMEDOODLE',
    GAME2048: 'GAME2048',
    GAMECROSS: 'GAMECROSS',
    GAMEMATCH3: 'GAMEMATCH3',
    GAMERUNNER: 'GAMERUNNER',
    DESKTOP: 'DESKTOP',
    FINISH: 'FINISH',
    PLUG: 'PLUG',
    SEX: 'SEX',
}

export const NEXT_SCREENS = {
    [SCREENS.INTROREG]: SCREENS.REG,
}
