export const SCREENS = {
    INTROREG: 'INTROREG',
    INTRO: 'INTRO',
    REG: 'REG',
    WAITING: 'WAITING',
    INTRO_RULES: 'INTRO_RULES',
    PROFILE: 'PROFILE',
    LOBBY: 'LOBBY',
    STORE: 'STORE',
    AWARDS: 'AWARDS',
    RULES: 'RULES',
    GAMES: 'GAMES',
    GAMECATCH: 'GAMECATCH',
    GAME2048: 'GAME2048',
    GAMECROSS: 'GAMECROSS',
    GAMEMATCH3: 'GAMEMATCH3',
    GAMERUNNER: 'GAMERUNNER',
    DESKTOP: 'DESKTOP',
    FINISH: 'FINISH',
    PLUG: 'PLUG',
    SEX: 'SEX',
    MINIGAMES: 'MINIGAMES'
}

export const NEXT_SCREENS = {
    [SCREENS.INTRO]: SCREENS.INTROREG,
    [SCREENS.INTROREG]: SCREENS.REG,
    [SCREENS.REG]: SCREENS.SEX,
}
