export const shopInfo = [
  {
    id: 'fu1',
    facTitle: 'ФУ Москва - Финансовый факультет',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 5, title: 'Обложка на студенческий', cost: 1400, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 8, title: 'Картхолдер', cost: 1850, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитсами и джибитсы', cost: 2200, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 10, title: 'Д. Миллер «Правила инвестирова-ния»', cost: 2450, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 12, title: 'Подставка для ноутбука', cost: 2900, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 4, week: 2, testAmount: 4, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 4, week: 2, testAmount: 4, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 21, title: 'Сертификат 2000р.:\nонлайн-курс (инвестиции)', cost: 6000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 24, title: 'Подарочный сертификат в Фитмост 3000 р.', cost: 7350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 26, title: 'Экшн-камера', cost: 8650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'fu2',
    facTitle: 'ФУ Москва - Факультет налогов, аудита и бизнес-анализа',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true  },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 7, week: 1, testAmount: 7, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 8, week: 1, testAmount: 8, isInfiniteAmount: false },
      { id: 5, title: 'Обложка на студенческий', cost: 1400, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 8, title: 'Картхолдер', cost: 1850, amount: 7, week: 1, testAmount: 7, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитсами и джибитсы', cost: 2200, amount: 5, week: 2, testAmount: 5, isInfiniteAmount: false },
      { id: 10, title: 'Д. Миллер «Правила инвестирова-ния»', cost: 2450, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 12, title: 'Подставка для ноутбука', cost: 2900, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 7, week: 2, testAmount: 7, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 9, week: 2, testAmount: 9, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 8, week: 3, testAmount: 8, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 5, week: 3, testAmount: 5, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 9, week: 3, testAmount: 9, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 5, week: 3, testAmount: 5, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 7, week: 3, testAmount: 7, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 6, week: 4, testAmount: 6, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 6, week: 4, testAmount: 6, isInfiniteAmount: false },
      { id: 29, title: 'Ортопед-\nподушка', cost: 7000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 31, title: 'Сертификат в читай-город 3000 р.', cost: 8350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 26, title: 'Экшн-камера', cost: 8650, amount: 4, week: 4, testAmount: 4, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 4, week: 4, testAmount: 4, isInfiniteAmount: false }
    ]
  },
  {
    id: 'vshe1',
    facTitle: 'НИУ ВШЭ Москва - Факультет экономических наук',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 7, week: 1, testAmount: 7, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 8, title: 'Картохолдер', cost: 1850, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 28, title: 'Сертификат Ozon 300 р.', cost: 2000, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибистами и джибисты', cost: 2200, amount: 4, week: 2, testAmount: 4, isInfiniteAmount: false },
      { id: 10, title: 'Д. Миллер «Правила инвестирова-ния»', cost: 2450, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 5, week: 2, testAmount: 5, isInfiniteAmount: false },
      { id: 12, title: 'Подставка для ноутбука', cost: 2900, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 6, week: 2, testAmount: 6, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 5, week: 2, testAmount: 5, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 5, week: 3, testAmount: 5, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 5, week: 3, testAmount: 5, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 5, week: 3, testAmount: 5, isInfiniteAmount: false },
      { id: 21, title: 'Сертификат 2000р.:\nонлайн-курс (инвестиции)', cost: 6000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 4, week: 4, testAmount: 4, isInfiniteAmount: false },
      { id: 29, title: 'Ортопед-\nподушка', cost: 7000, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 31, title: 'Сертификат в читай-город 3000 р.', cost: 8350, amount: 4, week: 4, testAmount: 4, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false }
    ]
  },
  {
    id: 'vshe2',
    facTitle: 'НИУ ВШЭ Москва - Международный институт экономики и финансов',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 8, title: 'Картхолдер', cost: 1850, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 10, title: 'Д. Миллер «Правила инвестирова-ния»', cost: 2450, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 29, title: 'Ортопед-\nподушка', cost: 7000, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'vshe3',
    facTitle: 'НИУ ВШЭ Москва - Факультет мировой экономики и мировой политики',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 7, week: 1, testAmount: 7, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 6, week: 1, testAmount: 6, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 6, week: 1, testAmount: 6, isInfiniteAmount: false },
      { id: 5, title: 'Обложка на студенческий', cost: 1400, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 6, week: 1, testAmount: 6, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 8, title: 'Картохолдер', cost: 1850, amount: 6, week: 1, testAmount: 6, isInfiniteAmount: false },
      { id: 28, title: 'Сертификат Ozon 300 р.', cost: 2000, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибистами и джибисты', cost: 2200, amount: 4, week: 2, testAmount: 4, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 12, title: 'Подставка для ноутбука', cost: 2900, amount: 4, week: 2, testAmount: 4, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 6, week: 2, testAmount: 6, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 8, week: 2, testAmount: 8, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер.', cost: 3700, amount: 7, week: 3, testAmount: 7, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 7, week: 3, testAmount: 7, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 21, title: 'Онлайн-курс про инвестиции/финансы (подарочный сертификат на 2000 р.)', cost: 6000, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 5, week: 4, testAmount: 5, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 5, week: 4, testAmount: 5, isInfiniteAmount: false },
      { id: 24, title: 'Подарочный сертификат в Фитмост 3000 р.', cost: 7350, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 31, title: 'Сертификат в читай-город 3000 р.', cost: 8350, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'mgimo1',
    facTitle: 'МГИМО Москва - Международные экономические отношения',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 8, title: 'Картхолдер', cost: 1850, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 29, title: 'Ортопед-\nподушка', cost: 7000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 24, title: 'Подарочный сертификат в Фитмост 3000 р.', cost: 7350, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false }
    ]
  },
  {
    id: 'resh',
    facTitle: 'РЭШ Москва - Все направления',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 1, title: 'Шопер', cost: 950, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 5, title: 'Обложка на студенческий', cost: 1400, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитсами и джибитсы', cost: 2200, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 15, title: 'Книга "Маги рынка. Секреты успешной торговли от топовых трейдеров"', cost: 3700, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 26, title: 'Экшн-камера', cost: 8650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'fu3',
    facTitle: 'ФУ - Факультет экономики и бизнеса',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 2, title: 'Шоколадный слиток золота', cost: 800, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 1, title: 'Шопер', cost: 950, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 6, week: 1, testAmount: 6, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 8, title: 'Картхолдер', cost: 1850, amount: 5, week: 1, testAmount: 5, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитсами и джибитсы', cost: 2200, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 10, title: 'Д. Миллер «Правила инвестирова-ния»', cost: 2450, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 12, title: 'Подставка для ноутбука', cost: 2900, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 13, title: 'Ежедневник', cost: 3150, amount: 6, week: 2, testAmount: 6, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 5, week: 2, testAmount: 5, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 6, week: 3, testAmount: 6, isInfiniteAmount: false },
      { id: 21, title: 'Сертификат 2000р.:\nонлайн-курс (инвестиции)', cost: 6000, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 24, title: 'Подарочный сертификат в Фитмост 3000 р.', cost: 7350, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'sgeu1',
    facTitle: 'СГЭУ (Самара) - Институт экономики предприятий',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 1, title: 'Шопер', cost: 950, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 5, title: 'Обложка на студенческий', cost: 1400, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 7, title: 'Сертификат на кофе 500 р.', cost: 1700, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 8, title: 'Картохолдер', cost: 1850, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитами и джибисты', cost: 2200, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 11, title: 'Чехол для ноутбука', cost: 2700, amount: 2, week: 2, testAmount: 2, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 16, title: 'Коврик для ПК с беспроводной зарядкой', cost: 4100, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 4, week: 3, testAmount: 4, isInfiniteAmount: false },
      { id: 19, title: 'Поясная сумка', cost: 5200, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 21, title: 'Онлайн-курс про инвестиции/финансы (подарочный сертификат на 2000 р.)', cost: 6000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false },
      { id: 30, title: 'Карьерная консультация 1 час', cost: 7650, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 31, title: 'Сертификат в читай-город 3000 р.', cost: 8350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false }
    ]
  },
  {
    id: 'mtusi1',
    facTitle: 'МТУСИ Москва - Факультет информационных технологий',
    items: [
      { id: 32, title: 'Билетик для розыгрыша', cost: 3000, amount: 'infinite', week: 1, testAmount: 'infinite', isInfiniteAmount: true, isTicket:  true },
      { id: 1, title: 'Шопер', cost: 950, amount: 3, week: 1, testAmount: 3, isInfiniteAmount: false },
      { id: 3, title: 'Книга\n«Атомные привычки» Д. Клир', cost: 1100, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 4, title: 'Антистресс с кнопочками', cost: 1250, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 6, title: 'Бутылка для воды', cost: 1550, amount: 4, week: 1, testAmount: 4, isInfiniteAmount: false },
      { id: 28, title: 'Сертификат Ozon 300 р.', cost: 2000, amount: 2, week: 1, testAmount: 2, isInfiniteAmount: false },
      { id: 9, title: 'Блокнот с джибитсами и джибитсы', cost: 2200, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 14, title: 'Футболка', cost: 3400, amount: 3, week: 2, testAmount: 3, isInfiniteAmount: false },
      { id: 15, title: 'Книга\n«Маги рынка»\nД. Швагер', cost: 3700, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 17, title: 'Термос', cost: 4450, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 18, title: 'Сертификат в читай-город 1000 р.', cost: 4850, amount: 3, week: 3, testAmount: 3, isInfiniteAmount: false },
      { id: 20, title: 'Дрипы verle', cost: 5600, amount: 2, week: 3, testAmount: 2, isInfiniteAmount: false },
      { id: 22, title: 'Карманный принтер', cost: 6350, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 23, title: 'Рюкзак', cost: 6650, amount: 2, week: 4, testAmount: 2, isInfiniteAmount: false },
      { id: 25, title: 'Проходка на День открытых дверей ВТБ в ноябре 2026', cost: 8000, amount: 1, week: 4, testAmount: 1, isInfiniteAmount: false },
      { id: 27, title: 'Проектор', cost: 9000, amount: 3, week: 4, testAmount: 3, isInfiniteAmount: false }
    ]
  }
];