export const shopInfo = [
  {
    id: 'fu1',
    "facTitle": "ФУ Москва - Финансовый факультет",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 5, "title": "Обложка на студенческий", "cost": 1400, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 8, "title": "Картхолдер", "cost": 1850, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 10, "title": "Д. Миллер «Правила инвестирова-ния»", "cost": 2450, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 12, "title": "Подставка для ноутбука", "cost": 2900, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 21, "title": "Сертификат 2000р.:\nонлайн-курс (инвестиции)", "cost": 6000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 24, "title": "Подарочный сертификат в Фитмост 3000 р.", "cost": 7350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 26, "title": "Экшн-камера", "cost": 8650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'fu2',
    "facTitle": "ФУ Москва - Факультет налогов, аудита и бизнес-анализа",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 8, "week": 1, "testAmount": 8 },
      { "id": 5, "title": "Обложка на студенческий", "cost": 1400, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 5, "week": 1, "testAmount": 5 },
      { "id": 8, "title": "Картхолдер", "cost": 1850, "amount": 5, "week": 1, "testAmount": 5 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 10, "title": "Д. Миллер «Правила инвестирова-ния»", "cost": 2450, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 12, "title": "Подставка для ноутбука", "cost": 2900, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 9, "week": 2, "testAmount": 9 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 8, "week": 3, "testAmount": 8 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 5, "week": 3, "testAmount": 5 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 9, "week": 3, "testAmount": 9 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 5, "week": 3, "testAmount": 5 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 7, "week": 3, "testAmount": 7 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 6, "week": 4, "testAmount": 6 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 6, "week": 4, "testAmount": 6 },
      { "id": 29, "title": "Ортопед-\nподушка", "cost": 7000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 31, "title": "Сертификат в читай-город 3000 р.", "cost": 8350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 26, "title": "Экшн-камера", "cost": 8650, "amount": 4, "week": 4, "testAmount": 4 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 4, "week": 4, "testAmount": 4 }
    ]
  },
  {
    id: 'vshe1',
    "facTitle": "НИУ ВШЭ Москва - Факультет экономических наук",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 6, "week": 1, "testAmount": 6 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 8, "title": "Картохолдер", "cost": 1850, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 28, "title": "Сертификат Ozon 300 р.", "cost": 2000, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 4, "week": 2, "testAmount": 4 },
      { "id": 10, "title": "Д. Миллер «Правила инвестирова-ния»", "cost": 2450, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 12, "title": "Подставка для ноутбука", "cost": 2900, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 5, "week": 3, "testAmount": 5 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 5, "week": 3, "testAmount": 5 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 5, "week": 3, "testAmount": 5 },
      { "id": 21, "title": "Сертификат 2000р.:\nонлайн-курс (инвестиции)", "cost": 6000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 4, "week": 4, "testAmount": 4 },
      { "id": 29, "title": "Ортопед-\nподушка", "cost": 7000, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 31, "title": "Сертификат в читай-город 3000 р.", "cost": 8350, "amount": 4, "week": 4, "testAmount": 4 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 3, "week": 4, "testAmount": 3 }
    ]
  },
  {
    id: 'vshe2',
    "facTitle": "НИУ ВШЭ Москва - Международный институт экономики и финансов",
    "items": [
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 8, "title": "Картхолдер", "cost": 1850, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 10, "title": "Д. Миллер «Правила инвестирова-ния»", "cost": 2450, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 29, "title": "Ортопед-\nподушка", "cost": 7000, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'vshe3',
    "facTitle": "НИУ ВШЭ Москва - Факультет мировой экономики и мировой политики",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 6, "week": 1, "testAmount": 6 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 6, "week": 1, "testAmount": 6 },
      { "id": 5, "title": "Обложка на студенческий", "cost": 1400, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 8, "title": "Картхолдер", "cost": 1850, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 28, "title": "Сертификат Ozon 300 р.", "cost": 2000, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 4, "week": 2, "testAmount": 4 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 12, "title": "Подставка для ноутбука", "cost": 2900, "amount": 4, "week": 2, "testAmount": 4 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 4, "week": 2, "testAmount": 4 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 8, "week": 2, "testAmount": 8 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер.", "cost": 3700, "amount": 7, "week": 3, "testAmount": 7 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 8, "week": 3, "testAmount": 8 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 21, "title": "Онлайн-курс про инвестиции/финансы (подарочный сертификат на 2000 р.)", "cost": 6000, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 5, "week": 4, "testAmount": 5 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 4, "week": 4, "testAmount": 4 },
      { "id": 24, "title": "Подарочный сертификат в Фитмост 3000 р.", "cost": 7350, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 31, "title": "Сертификат в читай-город 3000 р.", "cost": 8350, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'mgimo1',
    "facTitle": "МГИМО Москва - Международные экономические отношения",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 29, "title": "Ортопед-\nподушка", "cost": 7000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 24, "title": "Подарочный сертификат в Фитмост 3000 р.", "cost": 7350, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 1, "week": 4, "testAmount": 1 }
    ]
  },
  {
    id: 'resh',
    "facTitle": "РЭШ Москва - Все направления",
    "items": [
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 9, "title": "Блокнот с джибитами и джибисты", "cost": 2200, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 15, "title": "Книга \"Маги рынка. Секреты успешной торговли от топовых трейдеров\"", "cost": 3700, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 26, "title": "Экшн-камера", "cost": 8650, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'fu3',
    "facTitle": "ФУ - Факультет экономики и бизнеса",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 1, "week": 1, "testAmount": 1 },
      { "id": 2, "title": "Шоколадный слиток золота", "cost": 950, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 6, "week": 1, "testAmount": 6 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 8, "title": "Картхолдер", "cost": 1850, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 10, "title": "Д. Миллер «Правила инвестирова-ния»", "cost": 2450, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 12, "title": "Подставка для ноутбука", "cost": 2900, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 13, "title": "Ежедневник", "cost": 3150, "amount": 4, "week": 2, "testAmount": 4 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 5, "week": 2, "testAmount": 5 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 19, "title": "Поясная сумка", "cost": 5200, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 6, "week": 3, "testAmount": 6 },
      { "id": 21, "title": "Сертификат 2000р.:\nонлайн-курс (инвестиции)", "cost": 6000, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 4, "week": 4, "testAmount": 4 },
      { "id": 24, "title": "Подарочный сертификат в Фитмост 3000 р.", "cost": 7350, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'sgeu1',
    "facTitle": "СГЭУ (Самара) - Институт экономики предприятий",
    "items": [
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 5, "title": "Обложка на студенческий", "cost": 1400, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 7, "title": "Сертификат на кофе 500 р.", "cost": 1700, "amount": 4, "week": 1, "testAmount": 4 },
      { "id": 8, "title": "Картохолдер", "cost": 1850, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 9, "title": "Блокнот с джибитами и джибисты", "cost": 2200, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 11, "title": "Чехол для ноутбука", "cost": 2700, "amount": 2, "week": 2, "testAmount": 2 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 16, "title": "Коврик для ПК с беспроводной зарядкой", "cost": 4100, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 4, "week": 3, "testAmount": 4 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 21, "title": "Онлайн-курс про инвестиции/финансы (подарочный сертификат на 2000 р.)", "cost": 6000, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 3, "week": 4, "testAmount": 3 },
      { "id": 30, "title": "Карьерная консультация 1 час", "cost": 7650, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 31, "title": "Сертификат в читай-город 3000 р.", "cost": 8350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 2, "week": 4, "testAmount": 2 }
    ]
  },
  {
    id: 'mtusi1',
    "facTitle": "МТУСИ Москва - Факультет информационных технологий",
    "items": [
      { "id": 1, "title": "Шопер", "cost": 800, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 3, "title": "Книга\n«Атомные привычки» Д. Клир", "cost": 1100, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 4, "title": "Антистресс с кнопочками", "cost": 1250, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 6, "title": "Бутылка для воды", "cost": 1550, "amount": 3, "week": 1, "testAmount": 3 },
      { "id": 28, "title": "Сертификат Ozon 300 р.", "cost": 2000, "amount": 2, "week": 1, "testAmount": 2 },
      { "id": 9, "title": "Блокнот с джибитсами и джибитсы", "cost": 2200, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 14, "title": "Футболка", "cost": 3400, "amount": 3, "week": 2, "testAmount": 3 },
      { "id": 15, "title": "Книга\n«Маги рынка»\nД. Швагер", "cost": 3700, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 17, "title": "Термос", "cost": 4450, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 18, "title": "Сертификат в читай-город 1000 р.", "cost": 4850, "amount": 3, "week": 3, "testAmount": 3 },
      { "id": 20, "title": "Дрипы verle", "cost": 5600, "amount": 2, "week": 3, "testAmount": 2 },
      { "id": 22, "title": "Карманный принтер", "cost": 6350, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 23, "title": "Рюкзак", "cost": 6650, "amount": 2, "week": 4, "testAmount": 2 },
      { "id": 25, "title": "Проходка на День открытых дверей ВТБ в ноябре 2026", "cost": 8000, "amount": 1, "week": 4, "testAmount": 1 },
      { "id": 27, "title": "Проектор", "cost": 9000, "amount": 3, "week": 4, "testAmount": 3 }
    ]
  }
]