import gameoct1 from '../../../assets/images/lobby/game-oct1.webp';
import gameoct2 from '../../../assets/images/lobby/game-oct2.webp';
import gamerect from '../../../assets/images/lobby/gamerect.webp';
import investoct1 from '../../../assets/images/lobby/invest-oct1.webp';
import investoct2 from '../../../assets/images/lobby/invest-oct2.webp';
import investrect from '../../../assets/images/lobby/investrect.webp';
import quizoct1 from '../../../assets/images/lobby/quiz-oct1.webp';
import quizrect from '../../../assets/images/lobby/quizrect.webp';
import luckrect from '../../../assets/images/lobby/luckrect.webp';
import moneyrect from '../../../assets/images/lobby/moneyrect.webp';
import startTile from '../../../assets/images/lobby/startTile.webp';

import juice from '../../../assets/images/lobby/juice.webp';

import depos from '../../../assets/images/lobby/invest_depos.webp';
import shares from '../../../assets/images/lobby/invest_shares.webp';
import book from '../../../assets/images/lobby/invest_book.webp';
import cycle from '../../../assets/images/lobby/invest_cycle.webp';
import course from '../../../assets/images/lobby/invest_course.webp';
import obligation from '../../../assets/images/lobby/invest_obligation.webp';
import ticket from '../../../assets/images/lobby/invest_ticket.webp';
import sport from '../../../assets/images/lobby/invest_sport.webp';

import { SCREENS } from '../../../constants/screens';

export const CELL_WIDTH = 120;  // px
export const CELL_HEIGHT = 110; // px
export const START_CELL_WIDTH = 158;
export const START_CELL_HEIGHT = 126;
export const CHARACTER_WIDTH = 132;
export const CHARACTER_HEIGHT = 230;

export const MAX_MARGIN_LEFT = 170;   // чуть с запасом
export const MAX_MARGIN_TOP = 130;
export const MAX_CELL_W = START_CELL_WIDTH;
export const MAX_CELL_H = START_CELL_HEIGHT;

export const EXTRA_CELLS = 5;
/** Доп. ячейки вокруг вьюпорта, чтобы при быстром драге не мелькало */
export const CULL_BUFFER = 4;
/** Как часто пересчитывать видимые плитки во время драга (ms) */
export const VISIBLE_UPDATE_MS = 50;

export const MAX_X = 21;
export const MAX_Y = 8;

export const PAN_PADDING = {
    top: 120,
    right: -250,
    bottom: 250,
    left: 40,
};

// export const PAN_PADDING_2 = {}

//TODO: тексты просмотреть по фигме
export const GAME_CELLS = [
{
      id: "start-1",
      x: 0,
      y: 38,
      tileSrc: startTile,
      cellType: 'start',
      activeColor: '#004CDA',
      width: START_CELL_WIDTH,
      height: START_CELL_HEIGHT,
      marginLeft: 0,
      marginTop: -25,
      separators: [
        {
          marginLeft: START_CELL_WIDTH - 22,
          marginTop: 10,
        },
        {
          marginLeft: START_CELL_WIDTH - 15,
          marginTop: START_CELL_HEIGHT - 70,
        },
      ]
    },
{
      id: "w1_bonus_idea_award",
      x: 1,
      y: 38,
      tileSrc: moneyrect,
      marginLeft: 15,
      isRightSeparator: true,
      cellType: 'rect',
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Премия за идею",
      income: 200,
      cost: null,
      week: 1,
      name: "w1_bonus_idea_award",
      description: "На дейлике ты предложил решение для горящей задачи. Команда закрыла её быстрее, а тебе — премия. ВТБ предлагает высокий доход прямо со старта карьеры",
      separators: [
        {
          marginLeft: 115,
          marginTop: 30,
        },
        {
          marginLeft: 125,
          marginTop: 65,
        },
      ]
    },
{
      id: "w1_minigame_coin_runner",
      x: 2,
      y: 38,
      tileSrc: gameoct1,
      cellType: 'oct1',
      marginLeft: -5,
      isTopSeparator: true,
      marginTop: 5,
      type: "minigame",
      activeColor: '#479FFF',
      title: "Коин-раннер",
      screen: SCREENS.GAMERUNNER,
      incomes: [30, 120, 300],
      cost: null,
      week: 1,
      name: "w1_minigame_coin_runner",
      description: "Беги, лови коины, уворачивайся от лишних трат. Покажи класс за 30 секунд",
      separators: [
        {
          marginLeft: 23,
          marginTop: 10,
        },
        {
          marginLeft: 70,
          marginTop: 10,
        },
      ]
    },
  {
      id: "w1_luck_notification",
      x: 2,
      y: 37,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -20,
      marginTop: 45,
      isTopSeparator: true,
      type: "luck",
      activeColor: '#004CDA',
      title: "Уведомление",
      income: 700,
      cost: -350,
      week: 1,
      name: "w1_luck_notification",
      separators: [
        {
          marginLeft: -18,
          marginTop: 50,
        },
        {
          marginLeft: 52,
          marginTop: 50,
        },
      ],
      luckDescription: "Тебе пришло новое уведомление: «+10000 руб. от родителей: “Купи себе кроссовки, которые понравились!”» Удача сегодня на твоей стороне 😊",
      badluckDescription: "Тебе пришло новое уведомление: «Списание 499 руб. Ежемесячная подписка “Слушаем и обсуждаем”» Пуппуу… ты забыл отключить автопродление ненужной подписки 😊"
    },
{
      id: "w1_quiz_rich_or_broke",
      x: 2,
      y: 36,
      tileSrc: quizrect,
      cellType: 'rect',
      marginLeft: -50,
      marginTop: 80,
      separators: [
        {
          marginLeft: -48,
          marginTop: 84,
        },
        {
          marginLeft: 10,
          marginTop: 82,
        },
      ],
      isTopSeparator: true,
      type: "quiz",
      activeColor: '#479FFF',
      title: "Разбогател или прогорел?",
      income: 300,
      cost: null,
      week: 1,
      name: "w1_quiz_rich_or_broke",
      question: "Есть предложение, которое выглядит суперзаманчиво. Но ты же понимаешь… не всё золото, что блестит. Сделаешь правильный выбор — коины твои. Друг зовёт вложить всё в тему, которая «точно стрельнет». Ты…",
      answersInfo: [
        "А. Вкладывать всю сумму в один актив — большой риск. Если темка не стрельнет, то потеряешь все деньги сразу.",
        "B. Рискуй, но по чуть-чуть. Даже если не стрельнет — не критично.",
        "C. Инвестировать заёмные деньги опасно: если вложение не сработает, долг всё равно придётся возвращать, ещё и с процентами — анлак."
      ],
      answers: [
        "А. Вложу всё",
        "B. Вложу только то, что не страшно потерять.",
        "C. Возьму кредит и вложу."
      ],
      correctAnswer: 2,
    },
{
      id: "w1_investment_vtb_deposit",
      x: 2,
      y: 35,
      tileSrc: investoct1,
      cellType: 'oct1',
      marginLeft: -80,
      marginTop: 110,
      modalImage: depos,
      imgStyle: {
        width: 279,
        height: 274,
        marginTop: 20,
        marginBottom: 47,
      },
      separators: [
        {
          marginLeft: 10,
          marginTop: 124,
        },
        {
          marginLeft: 33,
          marginTop: 160,
        },
      ],
      type: "investment",
      activeColor: '#A171FF',
      title: "Вклад ВТБ",
      income: 150,
      incomeNextWeeks: 280,
      cost: -400,
      week: 1,
      name: "w1_investment_vtb_deposit",
      description: "Немного теории сейчас — больше пользы в будущем. Хорошее улучшение для старта игры. В ВТБ для твоей постоянной прокачки доступны курсы, тренинги и онлайн-библиотеки МИФ и Альпина. Для стажёров — отдельная программа обучения банковскому делу. Подробности ищи на сайте https://rabota.vtb.ru/internship/"
    },
{
      id: "w1_investment_financial_literacy_course",
      x: 3,
      y: 35,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -115,
      marginTop: 80,
      separators: [
        {
          marginLeft: -13,
          marginTop: 160,
        },
      ],
      modalImage: course,
      imgStyle: {
        width: 250,
        height: 223,
        marginTop: 4,
        marginLeft: 37,
        marginBottom: 87,
      },
      type: "investment",
      activeColor: '#A171FF',
      title: "Курс\nфинграмотности",
      isPercent: true,
      percent: 8,
      income: "+8%",
      incomePercentNextWeeks: 8,
      cost: -400,
      week: 1,
      name: "w1_investment_financial_literacy_course",
      description: <span>Деньги тоже должны работать. Открой вклад и начни получать стабильный доход каждую неделю{'\n\n'}В ВТБ для твоей постоянной прокачки доступны курсы, тренинги и онлайн-библиотеки МИФ и Альпина. Для стажёров — отдельная программа обучения банковскому делу. Подробности ищи на <a href="https://rabota.vtb.ru/internship/" target='_blank'>сайте</a></span>
    },
{
      id: "w1_luck_fashion_shopping",
      x: 4,
      y: 35,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -140,
      marginTop: 90,
      separators: [
        {
          marginLeft: -137,
          marginTop: 95,
        },
        {
          marginLeft: -63,
          marginTop: 95,
        },
      ],
      type: "luck",
      activeColor: '#004CDA',
      title: "Шопинг: модный лук",
      income: 700,
      cost: -350,
      week: 1,
      name: "w1_luck_fashion_shopping",
      luckDescription: "Сегодня было в планах купить новую одежду на осень. Плюс вайб! У твоего любимого бренда как раз скидки",
      badluckDescription: "Сегодня было в планах купить новую одежду на осень. Пупупу... дома ты обнаружил, что тебе продали фейк"
    },
{
      id: "w1_minigame_collect_capital",
      x: 4,
      y: 34,
      tileSrc: gameoct1,
      cellType: 'oct1',
      marginLeft: -160,
      marginTop: 120,
      separators: [
        {
          marginLeft: -80,
          marginTop: 125,
        },
        {
          marginLeft: -50,
          marginTop: 150,
        },
      ],
      type: "minigame",
      activeColor: '#479FFF',
      title: "Собери капитал",
      screen: SCREENS.GAME2048,
      incomes:[30, 120, 300],
      cost: null,
      week: 1,
      name: "w1_minigame_collect_capital",
      description: "Объединяй одинаковые активы и дорасти капитал до цели"
    },
{
      id: "w1_bonus_initiative_bonus",
      x: 5,
      y: 34,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -210,
      marginTop: 75,
      separators: [
        { marginLeft: -210, marginTop: 85 },
        { marginLeft: -140, marginTop: 82 },
      ],
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Бонус за инициативу",
      income: 200,
      cost: null,
      week: 1,
      name: "w1_bonus_initiative_bonus",
      description: "Ты заметил, что команда каждую неделю тратит кучу времени на создание презентаций и предложил идею, как это оптимизировать. Минус рутина — плюс бонус от начальства. В ВТБ инициатива не наказуема, а наоборот, ценится"
    },
{
      id: "w1_quiz_spare_money",
      x: 5,
      y: 33,
      tileSrc: quizrect,
      cellType: 'rect',
      marginLeft: -235,
      marginTop: 115,
      separators: [
        { marginLeft: -235, marginTop: 125 },
        { marginLeft: -185, marginTop: 115 },
      ],
      type: "quiz",
      activeColor: '#479FFF',
      title: "Свободные деньги",
      income: 300,
      cost: null,
      week: 1,
      name: "w1_quiz_spare_money",
      question: "Все счета оплачены, зарплата ещё не закончилась. Редкий момент! Что дальше?",
      answers: [
        "А. Пока просто полежат на карте.",
        "B. Закину на накопительный счёт — пусть капают проценты.",
        "C. Самое время заказать всё из корзины на маркетплейсе."
      ],
      answersInfo: [
        "А. Так деньги не работают, а просто лежат, пока ты думаешь, куда их потратить",
        "B. Даже небольшой процент лучше, чем хранить их без пользы",
        "C. не поддавайся на импульсивные покупки, а думай наперёд!"
      ],
      correctAnswer: 2,
    },
{
      id: "w1_investment_scooter_subscription",
      x: 5,
      y: 32,
      tileSrc: investoct2,
      cellType: 'oct2',
      marginLeft: -280,
      marginTop: 145,
      type: "investment",
      modalImage: cycle,
      zIndex: 6,
      separators: [
        { marginLeft: -275, marginTop: 155, zIndex: 5 },
        { marginLeft: -285, marginTop: 185, zIndex: 7 },
      ],
      imgStyle: {
        width: 291,
        height: 265,
        marginTop: 11,
        marginLeft: 36,
        marginBottom: 47,
      },
      activeColor: '#A171FF',
      title: "Купил велосипед",
      income: 50,
      incomeNextWeeks: 80,
      cost: -200,
      week: 1,
      name: "w1_investment_scooter_subscription",
      description: "Велосипед — чит-код против пробок. Конечно, свага не такая как от моноколеса, зато экономишь время в час пик и успеваешь больше"
    },
{
      id: "w1_luck_autumn_season",
      x: 4,
      y: 32,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -265,
      marginTop: 105,
      type: "luck",
      separators: [
        { marginLeft: -260, marginTop: 110 },
        { marginLeft: -190, marginTop: 110 },
      ],
      activeColor: '#004CDA',
      title: "Осенняя пора",
      income: 700,
      cost: -350,
      week: 1,
      name: "w1_luck_autumn_season",
      luckDescription: "Похолодало, пришло время доставать осеннюю куртку. Кажется, в кармане лежат забытые деньги! Сюдаааа. А рабочие поездки в ВТБ не проблема — компенсируют такси, чтобы ты спокойно добирался до нужных задач",
      badluckDescription: "Похолодало, и пошёл дождь. Кажется, зонтик остался дома и придётся вызывать такси. Минус вайб и минус деньги"
    },
{
      id: "w1_investment_vtb_shares",
      x: 4,
      y: 31,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -285,
      marginTop: 145,
      type: "investment",
      modalImage: shares,
      separators: [
        { marginLeft: -276, marginTop: 145 },
      ],
      imgStyle: {
        width: 243,
        height: 237,
        marginTop: 11,
        marginLeft: 63,
        marginBottom: 74,
      },
      activeColor: '#A171FF',
      title: "Акции ВТБ",
      income: 150,
      incomeNextWeeks: 280,
      cost: -400,
      week: 1,
      name: "w1_investment_vtb_shares",
      description: "Инвестируй в компании, в которые веришь. Если они растут, растут и твои возможности. А рабочие поездки в ВТБ не проблема — компенсируют такси, чтобы ты спокойно добирался до нужных задач"
    },
{
      id: "w1_minigame_match3",
      x: 4,
      y: 30,
      tileSrc: gameoct1,
      cellType: 'oct1',
      marginLeft: -300,
      marginTop: 175,
      type: "minigame",
      screen: SCREENS.GAMEMATCH3,
      separators: [
        { marginLeft: -220, marginTop: 180 },
        { marginLeft: -190, marginTop: 210 },
      ],
      activeColor: '#479FFF',
      title: "Собери капитал",
      incomes: [30, 120, 300],
      cost: null,
      week: 1,
      name: "w1_minigame_match3",
      description: "Объединяй одинаковые активы и дорасти капитал до цели"
    },
{
      id: "w1_bonus_vacation",
      x: 5,
      y: 30,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -345,
      marginTop: 135,
      type: "bonus",
      activeColor: '#5E67E8',
      title: "В отпуске,\nпью джус",
      modalImage: juice,
      separators: [
  { marginLeft: -250, marginTop: 160 },
  { marginLeft: -240, marginTop: 215 },
],
      imgStyle: {
          position: 'absolute',
          left: '50%',
          top: '5%',
          transform: 'translateX(-50%)',
          width: 198,
          height: 337,
      },
      income: 200,
      cost: null,
      week: 1,
      name: "w1_bonus_vacation",
      description: "А вот и отпускные — лови +3 дня отдыха от ВТБ.\n\nМного зарабатывать не равно мало отдыхать!"
    },
{
      id: "w1_luck_bank_push",
      x: 6,
      y: 30,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -370,
      marginTop: 145,
      type: "luck",
      separators: [
      { marginLeft: -275, marginTop: 170 },
      { marginLeft: -265, marginTop: 225 },
    ],
      activeColor: '#004CDA',
      title: "Пуш от банка",
      income: 700,
      cost: -350,
      week: 1,
      name: "w1_luck_bank_push",
      luckDescription: "Тебе пришло новое уведомление: «Начислен кэшбэк...» Как неожиданно и приятно? а для сотрудников ВТБ действуют бонус от банка и программы лояльности, чтобы кэшбэк был приятнее, а оплата услуг — всегда вовремя",
      badluckDescription: "Тебе пришло новое уведомление: «Списана оплата за подписку на киносервис». Помнишь, как брал её за 1Р на пробный период? Как всегда не вовремя?"
    },
{
      id: "w1_investment_finance_conference_ticket",
      x: 7,
      y: 30,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -395,
      marginTop: 155,
      type: "investment",
      separators: [
        { marginLeft: -285, marginTop: 210, zIndex: 3 },
        { marginLeft: -295, marginTop: 240, zIndex: 6 },
      ],
      modalImage: ticket,
      imgStyle: {
        width: 274,
        height: 211,
        marginTop: 28,
        marginLeft: 65,
        marginBottom: 101,
      },
      activeColor: '#A171FF',
      isPercent: true,
      percent: 8,
      title: "Билет на конференцию финансистов",
      income: "+8%",
      incomePercentNextWeeks: 8,
      cost: -400,
      week: 1,
      name: "w1_investment_finance_conference_ticket",
      description: <span>Хороший нетворкинг решает. Полезные знакомства и свежий взгляд помогают замечать новые возможности{'\n\n'}А ВТБ регулярно проводит полезные мероприятия для твоего развития. Ищи их на <a href={"https://rabota.vtb.ru/internship/"} target='_blank'>карьерном сайте ВТБ</a></span>
    },
{
      id: "w1_quiz_70_discount",
      x: 8,
      y: 30,
      tileSrc: quizoct1,
      cellType: 'oct1',
      marginLeft: -410,
      marginTop: 200,
      type: "quiz",
      activeColor: '#479FFF',
      title: "Скидка 70%!",
      separators: [
        { marginLeft: -380, marginTop: 283, zIndex: 5, },
        { marginLeft: -320, marginTop: 280, zIndex: 5, },
      ],
      income: 300,
      cost: null,
      week: 1,
      name: "w1_quiz_70_discount",
      question: "Твоя модель телефона устарела, хочется новый... Скроллишь ленту и попадается баннер: «Новый смартфон в рассрочку без первого взноса». Как поступишь?",
      answers: [
        "А. Беру не раздумывая.",
        "B. Изучу условия и посчитаю переплату.",
        "C. Возьму сразу два — второй потом пригодится."
      ],
      answersInfo: [
        "А. Хорошо звучит, но не факт, что выгодно",
        "B. Грамотные действия и отсутствие переплаты",
        "C. Запасные деньги звучит лучше, чем запасной телефон, не думаешь?"
      ],
      correctAnswer: 2,
    },
{
      id: "w1_investment_gym_membership",
      x: 8,
      y: 31,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -385,
      marginTop: 165,
      zIndex: 15,
      separators: [
        { marginLeft: -360, marginTop: 240, zIndex: 16, },
        { marginLeft: -290, marginTop: 240, zIndex: 16, },
      ],
      type: "investment",
      modalImage: sport,
      imgStyle: {
        width: 282,
        height: 206,
        marginTop: 13,
        marginLeft: 75,
        marginBottom: 58,
      },
      activeColor: '#A171FF',
      title: "Абонемент в спортзал",
      income: 50,
      incomeNextWeeks: 80,
      cost: -200,
      week: 1,
      name: "w1_investment_gym_membership",
      description: "Забота о здоровье — тоже инвестиция: энергии больше, стресса меньше. ВТБ порадует скидками на спортзалы, а ещё у него есть свои спортивные сообщества"
    },
{
      id: "w1_minigame_finance_doodle_jump",
      x: 8,
      y: 32,
      zIndex: 17,
      tileSrc: gamerect,
      separators: [
      { marginLeft: -340, marginTop: 200, zIndex: 18, },
      { marginLeft: -270, marginTop: 200,  zIndex: 18 },
    ],
      cellType: 'rect',
      marginLeft: -365,
      marginTop: 125,
      type: "minigame",
      screen: SCREENS.GAMEDOODLE,
      activeColor: '#479FFF',
      title: "Финансовый Doodle Jump",
      incomes: [30, 120, 300],
      cost: null,
      week: 1,
      name: "w1_minigame_finance_doodle_jump",
      description: "Прыгай по возможностям, избегай препятствий и поднимись до финала"
    },
{
      id: "w1_luck_past_returns",
      x: 8,
      y: 33,
      tileSrc: luckrect,
      zIndex: 18,
      cellType: 'rect',
      separators: [
        { marginLeft: -265, marginTop: 170, zIndex: 19 },
        { marginLeft: -240, marginTop: 160, zIndex: 19 },
      ],
      marginLeft: -345,
      marginTop: 85,
      type: "luck",
      activeColor: '#004CDA',
      title: "Всплыло из прошлого",
      income: 700,
      cost: -350,
      week: 1,
      name: "w1_luck_past_returns",
      luckDescription: "День начинается не с кофе... А с приятных новостей! Пришла компенсация мобильной связи от ВТБ",
      badluckDescription: "День начинается не с кофе... А с неприятных новостей! Какая-то старая подписка списала деньги"
    },
{
      id: "w1_investment_bonds",
      x: 8,
      y: 34,
      tileSrc: investoct1,
      cellType: 'oct1',
      marginLeft: -285,
      marginTop: 60,
      zIndex: 19,
      separators: [
        { marginLeft: -185, marginTop: 135, zIndex: 20 },
      ],
      type: "investment",
      modalImage: obligation,
      imgStyle: {
        width: 300,
        height: 300,
        marginTop: -12,
        marginLeft: 75,
        marginBottom: 56,
      },
      activeColor: '#A171FF',
      title: "Облигации",
      income: 150,
      incomeNextWeeks: 280,
      cost: -400,
      week: 1,
      name: "w1_investment_bonds",
      description: "Не хайп, зато надёжно. Хороший способ постепенно увеличивать капитал"
    },
{
      id: "w1_bonus_good_vibes",
      x: 9,
      y: 34,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -300,
      marginTop: 110,
      separators: [
        { marginLeft: -205, marginTop: 130 },
        { marginLeft: -195, marginTop: 175 },
      ],
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Плюс вайб",
      income: 200,
      cost: null,
      week: 1,
      name: "w1_bonus_good_vibes",
      description: "Сделал крутую презентацию — все в восторге. Команда довольна, а тебе начислили бонус. Собрал дашборд, который наконец-то показывает вообще всё. Команда в восторге, а тебе начислили бонус"
    },
{
      id: "w1_investment_investing_book",
      x: 10,
      y: 34,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -325,
      marginTop: 115,
      type: "investment",
      modalImage: book,
      separators: [
        { marginLeft: -238, marginTop: 130 },
        { marginLeft: -220, marginTop: 158 },
      ],
      imgStyle: {
        width: 197,
        height: 153,
        marginTop: 11,
        marginLeft: 145,
        marginBottom: 59,
      },
      activeColor: '#A171FF',
      title: "Книга об инвестициях",
      isPercent: true,
      percent: 8,
      income: "+8%",
      incomePercentNextWeeks: 8,
      cost: -400,
      week: 1,
      name: "w1_investment_investing_book",
      description: "Вместо вечернего скролла ленты с мемами — пара глав. Теперь принимать финансовые решения станет проще\n\nОсобенно проще принимать решения в сильной экспертной команде единомышленников в ВТБ"
    },
{
      id: "w1_minigame_financial_flow",
      x: 11,
      y: 34,
      tileSrc: gameoct2,
      cellType: 'oct2',
      marginLeft: -353,
      marginTop: 95,
      type: "minigame",
      screen: SCREENS.GAMECROSS,
      activeColor: '#479FFF',
      title: "Финансовый поток",
      incomes: [30, 120, 300],
      cost: null,
      week: 1,
      name: "w1_minigame_financial_flow",
      description: "Пересекай поток трат и рисков и доберись до финала"
    },
{
      id: "start-2",
      x: 11,
      y: 33,
      tileSrc: startTile,
      cellType: 'start',
      activeColor: '#004CDA',
      width: START_CELL_WIDTH,
      height: START_CELL_HEIGHT,
      marginTop: 50,
      marginLeft: -320,
      week: 2,
      separators: [
      { marginLeft: -296, marginTop: 45 },
    ],
    },
{
      id: "w2_bonus_first_promotion",
      x: 11,
      y: 32,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -320,
      marginTop: 85,
      separators: [
        { marginLeft: -306, marginTop: 85 },
        { marginLeft: -250, marginTop: 90 },
      ],
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Первое повышение",
      income: 250,
      cost: null,
      week: 2,
      name: "w2_bonus_first_promotion",
      description: "Спустя полгода хорошей работы тебя повысили! в ВТБ результаты замечают"
    },
{
      id: "w2_minigame_coin_runner",
      x: 11,
      y: 31,
      tileSrc: gamerect,
      cellType: 'rect',
      marginLeft: -340,
      marginTop: 120,
      separators: [
        { marginLeft: -325, marginTop: 120 },
        { marginLeft: -270, marginTop: 125 },
      ],
      type: "minigame",
      activeColor: '#479FFF',
      title: "Коин-раннер",
      incomes: [50, 150, 400],
      cost: null,
      week: 2,
      name: "w2_minigame_coin_runner",
      description: "Беги, лови коины, уворачивайся от лишних трат. Покажи класс за 25 секунд"
    },
{
      id: "w2_luck_notification",
      x: 11,
      y: 30,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -360,
      marginTop: 155,
      separators: [
        { marginLeft: -345, marginTop: 155 },
        { marginLeft: -295, marginTop: 160 },
      ],
      type: "luck",
      activeColor: '#004CDA',
      title: "Уведомление",
      income: 950,
      cost: -450,
      week: 2,
      name: "w2_luck_notification",
      luckDescription: "Тебе пришло новое уведомление: «Вместе с заказом на маркетплейсе тебе начислили бонус. Немного, но всё равно приятно»",
      badluckDescription: "Тебе пришло новое уведомление: «За онлайн-платёж списалась солидная комиссия. Надо было внимательнее читать условия оплаты...»"
    },
{
      id: "w2_quiz_higher_stakes",
      x: 11,
      y: 29,
      tileSrc: quizoct1,
      cellType: 'oct1',
      marginLeft: -380,
      marginTop: 185,
      separators: [
        { marginLeft: -380, marginTop: 205 },
        { marginLeft: -385, marginTop: 225, zIndex: 12 },
      ],
      type: "quiz",
      activeColor: '#479FFF',
      title: "Ставки повышаются",
      income: 400,
      cost: null,
      week: 2,
      name: "w2_quiz_higher_stakes",
      question: "Недавно ты купил акции, а сегодня они значительно выросли в цене. Как поступишь? Сделаешь правильный выбор — коины твои.",
      answers: [
        "А. Зафиксирую прибыль и продам все акции (неверно). Полностью выходить из инвестиций только из-за краткосрочного роста — не всегда лучшее решение. Важно учитывать свою долгосрочную стратегию",
        "B. Проанализирую рынок и скорректирую свой план (верно). Принимай решение, взвесив всё, а не действуй сгоряча",
        "C. Куплю еще этих же акций, пока они растут (неверно). Рост цены не гарантирует, что он продолжится. Прежде чем увеличивать вложения, важно правильно оценить риски"
      ],
      correctAnswer: 2,
    },
{
      id: "w2_investment_carsharing_subscription",
      x: 10,
      y: 29,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -365,
      marginTop: 140,
      separators: [
        { marginLeft: -355, marginTop: 140 },
        { marginLeft: -295, marginTop: 145 },
      ],
      type: "investment",
      activeColor: '#A171FF',
      title: "Подписка на каршеринг",
      income: 200,
      incomeNextWeeks: 400,
      cost: -550,
      week: 2,
      name: "w2_investment_carsharing_subscription",
      description: "Велосипед — это, конечно, хорошо, но хочется больше комфорта... Есть вайб обкатать полученные права?"
    },
{
      id: "w2_investment_negotiation_course",
      x: 10,
      y: 28,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -390,
      marginTop: 175,
      separators: [
        { marginLeft: -380, marginTop: 175 },
        { marginLeft: -320, marginTop: 180 },
      ],
      type: "investment",
      activeColor: '#A171FF',
      title: "Курс коммуникации и переговоров",
      isPercent: true,
      percent: 8,
      income: "+8%",
      incomePercentNextWeeks: 8,
      cost: -550,
      week: 2,
      name: "w2_investment_negotiation_course",
      description: "Умение правильно вести переговоры и договариваться приблизит тебя к выгодной сделке"
    },
{
      id: "w2_luck_delivery",
      x: 10,
      y: 27,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -410,
      marginTop: 210,
      separators: [
        { marginLeft: -400, marginTop: 210 },
        { marginLeft: -350, marginTop: 215 },
      ],
      type: "luck",
      activeColor: '#004CDA',
      title: "Доставка",
      income: 950,
      cost: -450,
      week: 2,
      name: "w2_luck_delivery",
      luckDescription: "Сервис доставки еды подарил тебе бесплатную пищу в честь дня рождения компании",
      badluckDescription: "Упс... доставка оказалась платной, придётся заплатить"
    },
{
      id: "w2_minigame_collect_capital",
      x: 10,
      y: 26,
      tileSrc: gameoct1,
      cellType: 'rect',
      marginLeft: -435,
      marginTop: 235,
      separators: [
        { marginLeft: -363, marginTop: 240 },
        { marginLeft: -335, marginTop: 265, },
      ],
      type: "minigame",
      activeColor: '#479FFF',
      title: "Собери капитал",
      incomes: [50, 150, 400],
      cost: null,
      week: 2,
      name: "w2_minigame_collect_capital",
      description: "Объединяй одинаковые активы и дорасти капитал до цели"
    },
{
      id: "w2_bonus_quarterly_report_bonus",
      x: 11,
      y: 26,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -485,
      marginTop: 190,
      separators: [
        { marginLeft: -395, marginTop: 210 },
        { marginLeft: -385, marginTop: 270 },
      ],
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Бонус за квартальный отчёт",
      income: 250,
      cost: null,
      week: 2,
      name: "w2_bonus_quarterly_report_bonus",
      description: "Ты подготовил подробный и качественный отчёт по итогам квартала: не только собрал и проверил все данные, но и представил их в понятном виде. В ВТБ ценят внимание к деталям и умение превращать огромный массив информации в выводы"
    },
{
      id: "w2_quiz_vtb_call",
      x: 12,
      y: 26,
      tileSrc: quizrect,
      cellType: 'rect',
      marginLeft: -515,
      marginTop: 200,
      separators: [
        { marginLeft: -425, marginTop: 220 },
        { marginLeft: -415, marginTop: 280 },
      ],
      type: "quiz",
      activeColor: '#479FFF',
      title: "Звонок из ВТБ",
      income: 400,
      cost: null,
      week: 2,
      name: "w2_quiz_vtb_call",
      question: "У тебя зазвонил телефон. Человек на проводе назвал тебя по имени и вежливо представился сотрудником банка. Говорит, что в твоё приложение кто-то зашёл и пытается перевести все деньги. Как поступишь?",
      answers: [
        "А. Послушаю и выполню все инструкции сотрудника, ведь он назвал меня по имени и вежливо общался со мной. Вряд ли это мошенники. Настоящие сотрудники банка никогда не звонят по телефону в таких ситуациях",
        "B. Сброшу звонок, опять какие-то мошенники звонят. Это не совсем верно, на всякий случай лучше проверить последние заходы в твой банк через СМС-оповещения или мобильное приложение. Ты также можешь позвонить в банк по официальному номеру самостоятельно",
        "C. Сброшу звонок и проверю мобильное приложение банка либо свяжусь с банком по официальному номеру самостоятельно (верно). Адекватные действия в таких ситуациях помогут тебе защитить свои данные и финансы. не поддавайся влиянию подозрительных лиц и всегда думай над своими действиями"
      ],
      correctAnswer: 3
    },
{
      id: "w2_investment_mutual_fund",
      x: 13,
      y: 26,
      tileSrc: investrect,
      cellType: 'rect',
      marginLeft: -545,
      marginTop: 210,
      separators: [
        { marginLeft: -450, marginTop: 230,  },
        { marginLeft: -445, marginTop: 290 },
      ],
      type: "investment",
      activeColor: '#A171FF',
      title: "ПИФ",
      income: 200,
      incomeNextWeeks: 400,
      cost: -550,
      week: 2,
      name: "w2_investment_mutual_fund",
      description: "Не хочешь сейчас самостоятельно выбрать, во что вложить деньги? Как насчёт купить пай фонда — так ты сможешь инвестировать сразу в разные активы"
    },
{
      id: "w2_luck_tax_deduction",
      type: "luck",
      x: 14,
      y: 26,
      tileSrc: luckrect,
      cellType: 'rect',
      marginLeft: -575,
      marginTop: 220,
      separators: [
        { marginLeft: -500, marginTop: 225 },
        { marginLeft: -550, marginTop: 220 },
      ],
      activeColor: '#004CDA',
      title: "Налоговый вычет",
      income: 950,
      cost: -450,
      week: 2,
      name: "w2_luck_tax_deduction",
      luckDescription: "Ты решил заранее сесть и разобраться, за что ты можешь получить налоговый вычет. У тебя всё получилось, а деньги уже пришли тебе на карту — Сегодня твой день!",
      badluckDescription: "Ты услышал, как знакомые говорят про оплату налога за вклады, но решил не вдаваться в подробности и не изучать информацию дома. В итоге тебе начислили пени за просрочку оплаты. Неприятно, но это тоже опыт!"
    },
{
      id: "w2_investment_work_laptop",
      type: "investment",
      x: 14,
      y: 25,
      tileSrc: investoct1,
      cellType: 'oct1',
      marginLeft: -585,
      marginTop: 250,
      separators: [
        { marginLeft: -475, marginTop: 305, },
        { marginLeft: -485, marginTop: 275,  },
      ],
      activeColor: '#A171FF',
      title: "Мощный ноут для работы",
      income: 50,
      incomeNextWeeks: 100,
      cost: -250,
      week: 2,
      name: "w2_investment_work_laptop",
      description: "Твой старый ноутбук долго запускается, разряжается за час и лагает при трёх открытых вкладках? Пришло время обновляться — сэкономь кучу времени и нервов"
    },
{
      id: "w2_minigame_match3",
      type: "minigame",
      x: 15,
      y: 25,
      tileSrc: gamerect,
      cellType: 'rect',
      marginLeft: -603,
      marginTop: 225,
      separators: [
        { marginLeft: -510, marginTop: 245, },
        { marginLeft: -500, marginTop: 305 },
      ],
      activeColor: '#479FFF',
      title: "Три в ряд",
      incomes: [50, 150, 400],
      cost: null,
      week: 2,
      name: "w2_minigame_match3",
      description: "Комбинируй одинаковые активы, запускай комбо и заработай как можно больше коинов"
    },
{
      id: "w2_bonus_refer_a_friend",
      type: "bonus",
      x: 16,
      y: 25,
      tileSrc: moneyrect,
      cellType: 'rect',
      marginLeft: -630,
      marginTop: 230,
      separators: [
        { marginLeft: -550, marginTop: 235, },
      ],
      activeColor: '#5E67E8',
      title: "Приведи друга по специальному предложению",
      income: 250,
      cost: null,
      week: 2,
      name: "w2_bonus_refer_a_friend",
      description: "Приведи друга по специальному реферальному коду ниже. Играть вместе – веселее, а ты получишь двойные бонусы. Реферальный код: XXXXXX. Сделай скриншот или запиши код, чтобы не потерять его. Он действует всего лишь один раз, то есть ты можешь привести одного друга по нему"
    },
{
      id: "w2_quiz_financial_habits",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Финансовые привычки",
      income: 400,
      cost: null,
      week: 2,
      name: "w2_quiz_financial_habits",
      question: "До зарплаты ещё далеко, а баланс на карте уже не радует. Деньги как будто стали исчезать сами. Как поступишь?",
      answers: [
        "А. Постараюсь меньше тратить в следующем месяце. Сложно оценить ситуацию без понимания твоих ежемесячных расходов. не слишком целесообразно меньше тратить, если ты не знаешь, на что уходят твои деньги",
        "B. Посмотрю историю операций за месяц и разберусь, на что уходит больше денег (верно). Анализ твоих расходов — первое, что нужно делать для управления бюджета и его оптимизации",
        "C. Перестану смотреть баланс, само как-то рассосется. У меня много пассивного дохода. Игнорирование подобных ситуаций может привести к ещё более худшим последствиям, кредитам и долгам"
      ],
      correctAnswer: 2,
    },
{
      id: "w2_investment_vending_machine",
      type: "investment",
      activeColor: '#A171FF',
      title: "Вендинговый автомат",
      income: 200,
      incomeNextWeeks: 400,
      cost: -550,
      week: 2,
      name: "w2_investment_vending_machine",
      description: "Часто посещая бизнес-центр, ты подумал, что тут можно поставить вендинговый автомат с едой и напитками для перекусов. Автомат будет работать без выходных и приносить тебе доход"
    },
{
      id: "w2_luck_airline_push",
      type: "luck",
      activeColor: '#004CDA',
      title: "Пуш от авиакомпании",
      income: 950,
      cost: -450,
      week: 2,
      name: "w2_luck_airline_push",
      luckDescription: "Ты выбирал билеты на самолёт для поездки на экономический форум. Тебе пришло новое уведомление от авиакомпании: «К сожалению, Ваше место было выкуплено до ещё до Вашей оплаты по технической ошибке. Однако мы готовы предложить Вам место в бизнес-классе по той же стоимости». Вот это luck!",
      badluckDescription: "Ты выбирал билеты на самолёт для поездки на экономический форум. Тебе пришло новое уведомление от авиакомпании: «К сожалению, Ваше место было выкуплено до ещё до Вашей оплаты по технической ошибке. Мы приносим свои извинения, деньги вернутся в течение месяца». Придётся заново покупать билеты..."
    },
{
      id: "w2_investment_language_course",
      type: "investment",
      activeColor: '#A171FF',
      title: "Курсы иностранного языка",
      isPercent: true,
      income: "+8%",
      percent: 8,
      incomePercentNextWeeks: 8,
      cost: -550,
      week: 2,
      name: "w2_investment_language_course",
      description: "Знание иностранного языка — это когда ты легко объясняешься в любой стране, смотришь фильмы без перевода, а ещё можешь читать литературу по финансам и экономике. В наше время знание хотя бы 1 иностранного языка — это не преимущество, а базовый минимум"
    },
{
      id: "w2_minigame_finance_doodle_jump",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый Doodle Jump",
      incomes: [50, 150, 400],
      cost: null,
      week: 2,
      name: "w2_minigame_finance_doodle_jump",
      description: "Прыгай по финансовым возможностям, избегай препятствий и поднимись до финала"
    },
{
      id: "w2_luck_currency_exchange",
      type: "luck",
      activeColor: '#004CDA',
      title: "Обмен валюты",
      income: 950,
      cost: -450,
      week: 2,
      name: "w2_luck_currency_exchange",
      luckDescription: "Ты решил устроить себе небольшой отпуск и поехать в другую страну. Новый город, новые впечатления... и ценники в незнакомой валюте. Пора подумать об обмене денег. Ты заранее посмотрел курс валюты и смог поменять деньги на выгодных условиях. Лишняя копеечка всегда пригодится в путешествии!",
      badluckDescription: "Ты решил устроить себе небольшой отпуск и поехать в другую страну. Новый город, новые впечатления... и ценники в незнакомой валюте. Ты решил не париться и обменять валюту прямо в аэропорту. Это было невыгодно, и пришлось заплатить большую комиссию"
    },
{
      id: "w2_quiz_salary_raise",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Повышение зарплаты",
      income: 400,
      cost: null,
      week: 2,
      name: "w2_quiz_salary_raise",
      question: "После повышения зарплаты у тебя появились лишние деньги. Кажется, можно позволить себе больше, чем раньше. Как поступишь с дополнительными деньгами?",
      answers: [
        "А. Сразу начну тратить, ведь теперь у меня новый лайфстайл: туда-сюда миллионер. Если расходы растут вместе с доходами, то накопить на что-то серьезное и стоящее становится тяжелее",
        "B. Часть прибавки буду откладывать или инвестировать, а оставшееся потрачу на себя (верно). Так ты одновременно улучшишь свою жизнь и увеличишь накопления",
        "C. Чтобы осуществить долгожданную покупку, мне нужно ещё не так много. Может быть, взять кредит или рассрочку?.. Рост дохода не означает, что тебе нужно увеличивать долговую нагрузку"
      ],
      correctAnswer: 2,
    },
{
      id: "w2_investment_iis",
      type: "investment",
      activeColor: '#A171FF',
      title: "ИИС",
      income: 200,
      incomeNextWeeks: 400,
      cost: -550,
      week: 2,
      name: "w2_investment_iis",
      description: "Инвестиции на долгий срок — это возможность не только приумножать капитал, но и получать дополнительную выгоду в виде налогового вычета. Возвращай часть уплаченного НДФЛ и используй эти деньги для новых целей"
    },
{
      id: "w2_bonus_mentor_of_the_month",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Наставник месяца",
      income: 250,
      cost: null,
      week: 2,
      name: "w2_bonus_mentor_of_the_month",
      description: "Ты помог коллеге разобраться с корпоративными правилами и сделал всё, чтобы он комфортно вошёл в рабочий ритм. В ВТБ ценят тех, кто помогает команде становиться сильнее"
    },
{
      id: "w2_minigame_financial_flow",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый поток",
      incomes: [50, 150, 400],
      cost: null,
      week: 2,
      name: "w2_minigame_financial_flow",
      description: "Пересекай поток трат и рисков и доберись до финала"
    },
{
      id: "w3_bonus_business_lounges",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Бизнес-залы",
      income: 350,
      cost: null,
      week: 3,
      name: "w3_bonus_business_lounges",
      description: "Получи доступ в бизнес-залы аэропортов и ж/д вокзалов — для сотрудников ВТБ доступны выгодные предложения от 2000+ партнёров. Настоящая премиум подписка на жизнь"
    },
{
      id: "w3_minigame_financial_flow",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый поток",
      incomes: [50, 200, 550],
      cost: null,
      week: 3,
      name: "w3_minigame_financial_flow",
      description: "Пересекай поток трат и рисков и доберись до финала"
    },
{
      id: "w3_luck_email",
      type: "luck",
      activeColor: '#004CDA',
      title: "Письмо в электронной почте",
      income: 1250,
      cost: -650,
      week: 3,
      name: "w3_luck_email",
      luckDescription: "Тебе на электронную почту пришло новое письмо: Ты выиграл билет на закрытую арт-выставку известного бренда. Вход в VIP-зону также обеспечен. ВТБ поддерживает культуру и сохраняет её наследие",
      badluckDescription: "Тебе на электронную почту пришло новое письмо: Ты попался на крючок... пропустил уведомление о регистрации на закрытую арт-выставку известного бренда. Придётся брать билет за свои деньги 😊"
    },
{
      id: "w3_quiz_digital_financial_assets",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Цифровые финансовые активы",
      income: 550,
      cost: null,
      week: 3,
      name: "w3_quiz_digital_financial_assets",
      question: "Ты решил попробовать современные финтех-инструменты и присматриваешься к ЦФА (цифровым финансовым активам) на драгоценные металлы. С чего начать? Сделаешь правильный выбор — коины твои.",
      answers: [
        "А. Вложить весь капитал в один вид ЦФА, ведь цифровые активы могут только постоянно расти. Любые инвестиции требуют диверсификации. не стоит вкладывать все средства в один инструмент, даже самый современный",
        "B. Проверить лицензию оператора информационной системы и инвестировать небольшую часть портфеля ✔ (верно). Разумный подход к новым технологиям позволяет протестировать инструмент с минимальными рисками для капитала",
        "С. Игнорировать ЦФА и хранить деньги в уже проверенных активах либо наличными. Отказ от новых финансовых инструментов ограничивает возможности для диверсификации и поиска более высокой доходности, а хранение значительной части средств в наличных не защищает капитал от инфляции"
      ],
      correctAnswer: 2,
    },
{
      id: "w3_investment_real_estate",
      type: "investment",
      activeColor: '#A171FF',
      title: "Приобретение недвижимости",
      income: 250,
      incomeNextWeeks: 500,
      cost: -700,
      week: 3,
      name: "w3_investment_real_estate",
      description: "Первоначальный взнос по ипотеке с эскроу-счетом и безопасным цифровым аккредитивом. Для сотрудников ВТБ ипотека становится менее страшной, а кредиты и страховки — чуть дешевле. Плюс расширенный кэшбэк"
    },
{
      id: "w3_investment_financial_resilience_book",
      type: "investment",
      activeColor: '#A171FF',
      title: "Книга по финансовой устойчивости",
      isPercent: true,
      income: "+8%",
      percent: 8,
      incomePercentNextWeeks: 8,
      cost: -700,
      week: 3,
      name: "w3_investment_financial_resilience_book",
      description: "Покупка книги на иностранном языке об управлении рисками и создании финансовой подушки безопасности. Финансовая грамотность обеспечена, бонус-загадочная аура"
    },
{
      id: "w3_luck_family_banking",
      type: "luck",
      activeColor: '#004CDA',
      title: "Семейный банкинг",
      income: 1250,
      cost: -650,
      week: 3,
      name: "w3_luck_family_banking",
      luckDescription: "Погода меняется с космической скоростью. На улице похолодало и кажется, что ты простыл. Хорошо, что сотрудникам ВТБ доступен расширенный ДМС. Забота о твоем здоровье и благополучии — цель компании",
      badluckDescription: "Погода меняется с космической скоростью. На улице похолодало и кажется, что ты простыл. Пришлось потратиться на лекарства. Болеть во взрослом возрасте — очень невыгодно"
    },
{
      id: "w3_minigame_match3",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Три в ряд",
      incomes: [50, 200, 550],
      cost: null,
      week: 3,
      name: "w3_minigame_match3",
      description: "Комбинируй одинаковые активы, запускай комбо и заработай как можно больше коинов"
    },
{
      id: "w3_bonus_free_consultation",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Бесплатная консультация",
      income: 350,
      cost: null,
      week: 3,
      name: "w3_bonus_free_consultation",
      description: "Тебе доступна бесплатная консультация с персональным инвестиционным советником. Получи рекомендации, подходящие именно тебе – успешный успех близко"
    },
{
      id: "w3_quiz_corporate_client",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Корпоративный клиент",
      income: 550,
      cost: null,
      week: 3,
      name: "w3_quiz_corporate_client",
      question: "К тебе как к сотруднику ВТБ пришёл посоветоваться друг: у него есть карты и счета в разных банках, и ему неудобно постоянно переключаться между несколькими приложениями для контроля бюджета. Что ты ему порекомендуешь?",
      answers: [
        "А. Записать все пароли и логины в заметки на телефоне, чтобы быстрее входить в каждое приложение. Хранить пароли в заметках небезопасно — при утере телефона мошенники могут получить доступ к счетам",
        "B. Закрыть все счета и пользоваться только наличными, чтобы не путаться. Отказ от банковских карт лишает тебя процента на остаток и современных способов оплаты, которые необходимы корпоративным клиентам",
        "C. Подключить сервис мультибанкинга в приложении ВТБ Онлайн, чтобы видеть баланс всех карт и счетов в одном месте (верно). Сервис открытого банкинга позволяет удобно и безопасно контролировать свои финансы в едином окне"
      ],
      correctAnswer: 3,
    },
{
      id: "w3_investment_electric_car",
      type: "investment",
      activeColor: '#A171FF',
      title: "Электромобиль",
      income: 100,
      incomeNextWeeks: 150,
      cost: -350,
      week: 3,
      name: "w3_investment_electric_car",
      description: "Подчёркнутый премиальный стиль, передовые экотехнологии, которые показывают статус"
    },
{
      id: "w3_luck_digital_ruble",
      type: "luck",
      activeColor: '#004CDA',
      title: "Цифровой рубль",
      income: 1250,
      cost: -650,
      week: 3,
      name: "w3_luck_digital_ruble",
      luckDescription: "Ты решил принять участие в тестировании Цифрового рубля. За оплаты в новой валюте тебе начислили уникальный цифровой бонус в рублях. Подробнее про Цифровой рубль тут: https://www.vtb.ru/fincult/lr/dr/",
      badluckDescription: "Ты решил принять участие в тестировании Цифрового рубля. Ты по ошибке, не разобравшись, перевёл Цифровые рубли не на тот счёт. Поддержка уже оформляет возврат, но пока придётся воспользоваться привычными средствами оплаты. Подробнее про Цифровой рубль тут: https://www.vtb.ru/fincult/lr/dr/"
    },
{
      id: "w3_investment_floating_rate_deposit",
      type: "investment",
      activeColor: '#A171FF',
      title: "Вклад с плавающей ставкой",
      income: 250,
      incomeNextWeeks: 500,
      cost: -700,
      week: 3,
      name: "w3_investment_floating_rate_deposit",
      description: "Крупную сумму можно положить на депозит с доходностью, привязанной к ключевой ставке, или разбить на несколько вкладов с разными сроками. Так ты получишь стабильный пассивный доход и легко подстроишься под изменения ставки ЦБ"
    },
{
      id: "w3_minigame_collect_capital",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Собери капитал",
      incomes: [50, 200, 550],
      cost: null,
      week: 3,
      name: "w3_minigame_collect_capital",
      description: "Объединяй одинаковые активы и дорасти капитал до цели"
    },
{
      id: "w3_investment_smartwatch",
      type: "investment",
      activeColor: '#A171FF',
      title: "Премиальные умные часы",
      income: 100,
      incomeNextWeeks: 150,
      cost: -350,
      week: 3,
      name: "w3_investment_smartwatch",
      description: "Гаджет, который держит под контролем твоё здоровье, а ВТБ заботится о твоём благополучии не меньше: расширенный ДМС, стоматология, поддержка семьи и выплаты при рождении ребенка"
    },
{
      id: "w3_quiz_preferential_mortgage",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Льготная ипотека",
      income: 550,
      cost: null,
      week: 3,
      name: "w3_quiz_preferential_mortgage",
      question: "Ты планируешь покупку собственной квартиры и рассматриваешь льготную ипотеку. Какое действие будет наиболее грамотным перед оформлением сделки?",
      answers: [
        "А. Зафиксировать условия, рассчитать комфортный ежемесячный платеж через ипотечный калькулятор и открыть эскроу-счёт (верно). Предварительный расчёт нагрузки и использование эскроу-счёта гарантируют безопасность твоих средств и финансовую стабильность. Подробнее про ипотеку и другие бонусы для сотрудников ВТБ: https://rabota.vtb.ru/benefits/",
        "B. Взять потребительский кредит на первоначальный взнос, чтобы не тратить личные сбережения. Дополнительный кредит существенно увеличит твою долговую нагрузку, и банк может отказать в ипотеке. Подробнее про ипотеку и другие бонусы для сотрудников ВТБ: https://rabota.vtb.ru/benefits/",
        "С. Подписать договор не читая, чтобы скорее забронировать понравившуюся квартиру. Ипотека — это долгосрочное обязательство. Все условия по ставкам, страховке и срокам нужно внимательно изучать до подписания. Подробнее про ипотеку и другие бонусы для сотрудников ВТБ: https://rabota.vtb.ru/benefits/"
      ],
      correctAnswer: 1,
    },
{
      id: "w3_bonus_refer_a_friend",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Приведи друга по специальному предложению",
      income: 350,
      cost: null,
      week: 3,
      name: "w3_bonus_refer_a_friend",
      description: "Приведи друга по специальному реферальному коду ниже. Играть вместе — веселее, а ты получишь двойные бонусы. Сделай скриншот или запиши код, чтобы не потерять его. Он действует всего лишь один раз, то есть ты можешь привести одного друга по нему. Прошла медиана игры — надо поднажать!"
    },
{
      id: "w3_luck_major_client",
      type: "luck",
      activeColor: '#004CDA',
      title: "Крупный клиент",
      income: 1250,
      cost: -650,
      week: 3,
      name: "w3_luck_major_client",
      luckDescription: "Ты потратил несколько недель на баг-репорт для системы одного крупного клиента. Разработчики быстро воспроизвели проблему по твоему описанию, исправили её уже в следующем обновлении, а коллеги поблагодарили тебя за внимательность. Иногда один баг-репорт экономит часы работы всей команды",
      badluckDescription: "Ты потратил несколько недель на баг-репорт для системы одного крупного клиента. Ты ограничился сообщением: «Что-то не работает». Разработчики не смогли воспроизвести ошибку, пришлось собирать информацию заново и тратить время всей команды"
    },
{
      id: "w3_investment_risk_management_workshop",
      type: "investment",
      activeColor: '#A171FF',
      title: "Воркшоп по риск-менеджменту и деривативам",
      isPercent: true,
      percent: 8,
      income: "+8%",
      incomePercentNextWeeks: 8,
      cost: -700,
      week: 3,
      name: "w3_investment_risk_management_workshop",
      description: "Пройди специальный тренинг по срочному рынку и рискам — овсой работой с фьючерсными контрактами и опционами для страхования твоего портфеля от валютных колебаний"
    },
{
      id: "w3_minigame_finance_doodle_jump",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый Doodle Jump",
      incomes: [50, 200, 550],
      cost: null,
      week: 3,
      name: "w3_minigame_finance_doodle_jump",
      description: "Прыгай по финансовым возможностям, избегай препятствий и поднимись до финала"
    },
{
      id: "w3_investment_investment_portfolio",
      type: "investment",
      activeColor: '#A171FF',
      title: "Инвестиционный портфель",
      income: 250,
      incomeNextWeeks: 500,
      cost: -700,
      week: 3,
      name: "w3_investment_investment_portfolio",
      description: "Помоги клиенту сформировать диверсифицированный инвестиционный портфель с учётом его целей и отношения к риску. Сделай так, чтобы его деньги работали эффективнее, а ты укрепил доверие клиента"
    },
{
      id: "w3_luck_property_tax",
      type: "luck",
      activeColor: '#004CDA',
      title: "Оплата имущественных налогов",
      income: 1250,
      cost: -650,
      week: 3,
      name: "w3_luck_property_tax",
      luckDescription: "Тебе пришло уведомление после того, как истёк срок уплаты имущественных налогов. Ты оплатил налог на имущество и транспорт через QR-код в приложении ВТБ в период специальной акции и получил отличный кешбэк!",
      badluckDescription: "Тебе пришло уведомление после того, как истёк срок уплаты имущественных налогов. Ты вспомнил про уплату налогов в последний момент. Пришлось платить не только сам налог, но и пусть небольшие, но неприятные пени за каждый день просрочки — минус вайб..."
    },
{
      id: "w3_quiz_loss_carryforward",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Сальдо убытков или убытки от сальдо?",
      income: 550,
      cost: null,
      week: 3,
      name: "w3_quiz_loss_carryforward",
      question: "У тебя был неудачный год по сделкам у одного брокера (убыток составил около 100 000 ₽), и удачный — у другого (прибыль около 150 000 ₽). Второй брокер удержал с этой прибыли НДФЛ. Как вернуть переплаченный налог?",
      answers: [
        "А. Ничего сделать нельзя: убытки у разных брокеров не суммируются и сгорают в конце года. Налоговый кодекс позволяет сальдировать (объединять) финансовые результаты по разным брокерским счетам за один налоговый период. Подробнее про сальдирование читай тут: https://www.vtb.ru/personal/investicii/help/nalogi/saldirovanie/",
        "B. Потребовать от первого брокера выплатить тебе компенсацию за убыточные сделки. Брокер лишь предоставляет доступ к торгам и удерживает налоги, но не несёт ответственности за твои торговые решения. Подробнее про сальдирование читай тут: https://www.vtb.ru/personal/investicii/help/nalogi/saldirovanie/",
        "C. Подать декларацию 3-НДФЛ в ФНС по окончании года, приложив справки о доходах от обоих брокеров, чтобы вернуть часть удержанного налога (верно). Сальдирование убытков позволяет уменьшить налогооблагаемую базу: НДФЛ должен уплачиваться только с чистой прибыли (50 000 ₽), а излишек удержанного налога ФНС вернёт на твой счёт. Подробнее про сальдирование читай тут: https://www.vtb.ru/personal/investicii/help/nalogi/saldirovanie/"
      ],
      correctAnswer: 3,
    },
{
      id: "w3_bonus_delegate_routine",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Делегируй рутину",
      income: 350,
      cost: null,
      week: 3,
      name: "w3_bonus_delegate_routine",
      description: "Лови сертификат на клининг: пусть воскресенье не превращается в ещё один рабочий день с уборкой. Вместо этого прогуляйся в парке"
    },
{
      id: "w3_minigame_coin_runner",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Коин-раннер",
      incomes: [50, 200, 550],
      cost: null,
      week: 3,
      name: "w3_minigame_coin_runner",
      description: "Беги, лови коины, уворачивайся от лишних трат. Покажи класс за 20 секунд"
    },
{
      id: "w4_bonus_hybrid_schedule",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Гибридный график",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_hybrid_schedule",
      description: "Сегодня ты решил поработать из дома. Минус дорога, плюс лишний час сна и продуктивности. В ВТБ есть гибридный формат работы для многих команд — балансировать работу и жизнь становится проще"
    },
{
      id: "w4_minigame_coin_runner",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Коин-раннер",
      incomes: [50, 300, 700],
      cost: null,
      week: 4,
      name: "w4_minigame_coin_runner",
      description: "Беги, лови коины, уворачивайся от лишних трат. Покажи класс за 20 секунд"
    },
{
      id: "w4_luck_business_trip",
      type: "luck",
      activeColor: '#004CDA',
      title: "Командировка",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_business_trip",
      luckDescription: "Первая рабочая командировка. ВТБ компенсирует все расходы, если правильно оформить документы. Рабочая поездка закончилась раньше. Тебе удалось провести дополнительный день в новом городе без лишних затрат",
      badluckDescription: "Первая рабочая командировка. ВТБ компенсирует все расходы, если правильно оформить документы. Ты потерял чек за расходы в командировке, компенсацию оформить не получилось"
    },
{
      id: "w4_quiz_american_race",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Волатильность акций",
      income: 700,
      cost: null,
      week: 4,
      name: "w4_quiz_american_race",
      question: "Ты купил акции и видишь по графику, что они то растут, то падают. Что делать в такой ситуации?",
      answers: [
        "А. Падения — это плохо, надо продавать. Стоимость акций может временно снижаться — это обычная ситуация на рынке. Продажа из-за паники может только зафиксировать убыток",
        "B. Краткосрочные колебания — это нормально, оставляем (верно). Инвестиции рассчитаны на долгий срок. Важно оценивать ситуацию спокойно и не менять план из-за краткосрочных колебаний",
        "C. Чем сильнее колебания — тем больше выгода, надо закупиться. Даже если цена кажется привлекательной, колебания не являются фактором выгоды. Лучше сохранять диверсификацию и инвестировать постепенно"
      ],
      correctAnswer: 2,
    },
{
      id: "w4_investment_global_market_etf",
      type: "investment",
      activeColor: '#A171FF',
      title: "Глобальный портфель",
      income: 1700,
      cost: null,
      week: 4,
      name: "w4_investment_global_market_etf",
      description: "Вместо выбора отдельных компаний ты покупаешь сразу целый набор активов. Купи акции со всего земного шара"
    },
{
      id: "w4_luck_office_cafe",
      type: "luck",
      activeColor: '#004CDA',
      title: "Обед",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_office_cafe",
      luckDescription: "Рабочий день в самом разгаре. В голове только один вопрос: \"А у нас будет что-то типа обеда?\" Посмотрим, чем закончится этот перерыв). Коллега угостил тебя обедом, как неожиданно и приятно",
      badluckDescription: "Рабочий день в самом разгаре. В голове только один вопрос: \"А у нас будет что-то типа обеда?\" Ты случайно оплатил заказ дважды, возврат будет позже"
    },
{
      id: "w4_bonus_corporate_psychologist",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Психологическая поддержка",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_corporate_psychologist",
      description: "После напряжённого проекта ты воспользовался бесплатной консультацией специалиста. Оплата у психолога действительно прошла – работать стало легче. В ВТБ сотрудникам доступна программа психологической поддержки"
    },
{
      id: "w4_minigame_finance_doodle_jump",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый Doodle Jump",
      incomes: [50, 300, 700],
      cost: null,
      week: 4,
      name: "w4_minigame_finance_doodle_jump",
      description: "Прыгай по финансовым возможностям, избегай препятствий и поднимись до финала"
    },
{
      id: "w4_luck_atm",
      type: "luck",
      activeColor: '#004CDA',
      title: "Снятие наличных",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_atm",
      luckDescription: "Тебе срочно понадобились наличные деньги. Казалось бы, обычная операция… Банкомат оказался рядом, очередей не было и не нужно платить комиссию, опачки!",
      badluckDescription: "Тебе срочно понадобились наличные деньги. Ближайший банкомат временно не работал, пришлось снимать деньги с комиссией и ехать на другой конец города… Минус деньги и время("
    },
{
      id: "w4_quiz_high_investment_income",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Значительный доход от инвестиций",
      income: 700,
      cost: null,
      week: 4,
      name: "w4_quiz_high_investment_income",
      question: "Ты получил значительный доход от инвестиций. Что стоит учитывать при работе с ними?",
      answers: [
        "А. С инвестиционного дохода могут удерживаться налоги (верно). Налоговый режим зависит от вида дохода и условий инвестирования, не забывай про это!",
        "B. Инвестиционный доход не облагается налогом. не весь инвестиционный доход освобождается от налогов. Для разных инструментов действуют разные правила, поэтому важно заранее изучить условия",
        "C. Вид инвестиционного дохода не влияет на налог с него. не весь инвестиционный доход освобождается от налогов. Для разных инструментов действуют разные правила, поэтому важно заранее изучить условия"
      ],
      correctAnswer: 1,
    },
{
      id: "w4_bonus_sports_community",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Спортивное сообщество",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_sports_community",
      description: "Ты присоединился к корпоративному забегу ВТБ и познакомился с коллегами из других команд. Отличный нетворкинг и заряд энергии, а также плюс вайб!"
    },
{
      id: "w4_luck_rent_payment_notification",
      type: "luck",
      activeColor: '#004CDA',
      title: "Уведомление о платеже за квартиру",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_rent_payment_notification",
      luckDescription: "Автоплатёж за ЖКХ. Работал ли он у меня или нет? Не помню... переживаешь, что пропустишь срок оплаты. Но всё сработало!",
      badluckDescription: "Автоплатёж за ЖКХ не сработал из-за недостатка средств на счёте, и появилась пеня. Перепутал счет или забыл положить на него деньги?"
    },
{
      id: "w4_investment_digital_assets",
      type: "investment",
      activeColor: '#A171FF',
      title: "Цифровые активы",
      income: 1250,
      cost: -950,
      week: 4,
      name: "w4_investment_digital_assets",
      description: "Выдели небольшую часть капитала на покупку цифрового актива, оборот которого разрешён российским законодательством. Такие инструменты могут заметно меняться в цене, поэтому важно соблюдать баланс в портфеле"
    },
{
      id: "w4_minigame_collect_capital",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Собери капитал",
      incomes: [50, 300, 700],
      cost: null,
      week: 4,
      name: "w4_minigame_collect_capital",
      description: "Объединяй одинаковые активы и дорасти капитал до цели"
    },
{
      id: "w4_investment_noise_canceling_headphones",
      type: "investment",
      activeColor: '#A171FF',
      title: "Шумоподавляющие наушники",
      income: 550,
      cost: -500,
      week: 4,
      name: "w4_investment_noise_canceling_headphones",
      description: "Концентрация выросла, работать стало комфортнее даже в опенспейсе. Слышу только то, что нужно!"
    },
{
      id: "w4_bonus_corporate_training",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Корпоративное обучение",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_corporate_training",
      description: "Ты успешно закончил внутреннюю программу развития и получил сертификат. В ВТБ обучение оплачивается и считается частью карьерного роста"
    },
{
      id: "w4_quiz_first_million",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Совет другу",
      income: 700,
      cost: null,
      week: 4,
      name: "w4_quiz_first_million",
      question: "Твой друг пришёл к тебе за советом: до его финансовой цели ещё далеко. Какой подход с большей вероятностью поможет достичь цель?",
      answers: [
        "А. Вложить все накопления в один высокодоходный актив. Высокая потенциальная доходность почти всегда сопровождается высоким риском. Для твоего друга этот риск необоснован",
        "B. Начать инвестировать только тогда, когда получится откладывать большие суммы. Даже небольшие, но регулярные вложения обычно эффективнее постоянного откладывания старта",
        "C. Инвестировать, постепенно увеличивая сумму по мере роста дохода (верно). Такой подход помогает формировать капитал без резких финансовых рисков и позволяет использовать эффект долгосрочного инвестирования. Такое подойдёт твоему другу!"
      ],
      correctAnswer: 3,
    },
{
      id: "w4_luck_cashback_surprise",
      type: "luck",
      activeColor: '#004CDA',
      title: "Кэшбэк",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_cashback_surprise",
      luckDescription: "Новый месяц – новые категории кэшбэка. Посмотрим, что приготовил банк на этот раз. Любимая категория месяца совпала с твоими расходами — кайф!",
      badluckDescription: "Новый месяц – новые категории кэшбэка. Перепутал категорию повышенного кэшбэка — мне кешбека мало, мне твои деньги всегда мало…"
    },
{
      id: "w4_bonus_extra_vacation_days",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "+2 дня к отпуску",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_extra_vacation_days",
      description: "Ты вспомнил, что у сотрудников ВТБ есть 2 дополнительных дня оплачиваемого отпуска. Отличный повод устроить себе длинные выходные и почилить"
    },
{
      id: "w4_minigame_match3",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Три в ряд",
      incomes: [50, 300, 700],
      cost: null,
      week: 4,
      name: "w4_minigame_match3",
      description: "Комбинируй одинаковые активы, запускай комбо и заработай как можно больше коинов"
    },
{
      id: "w4_luck_the_jacket",
      type: "luck",
      activeColor: '#004CDA',
      title: "Та самая куртка…",
      income: 1700,
      cost: -850,
      week: 4,
      name: "w4_luck_the_jacket",
      luckDescription: "Наступают холода… Вот та самая винтажная куртка, которая была у тебя в прошлом году. А что у нас в карманах?) Твой глазки нашел алмазик – в одном из карманов были забытые деньги. Маленький подарок от прошлой версии тебя",
      badluckDescription: "Наступают холода… Вот та самая винтажная куртка, которая была у тебя в прошлом году. Только старые чеки и просроченный купон на скидку в кафе. Да уж…"
    },
{
      id: "w4_investment_photo_booth",
      type: "investment",
      activeColor: '#A171FF',
      title: "Фотобудка",
      income: 1250,
      cost: -950,
      week: 4,
      name: "w4_investment_photo_booth",
      description: "Установи фотобудку в популярном торговом центре. В праздники очередь не заканчивается, а в будни посетителей меньше. Можно позвать знакомых сделать фоточку и прорекламировать место в соц. сетях"
    },
{
      id: "w4_quiz_matcha_with_coconut",
      type: "quiz",
      activeColor: '#479FFF',
      title: "Кофе на кокосовом",
      income: 700,
      cost: null,
      week: 4,
      name: "w4_quiz_matcha_with_coconut",
      question: "Выходишь из метро и идёшь в офис, как обычно берёшь в кофейне свой любимый напиток и вдруг думаешь... Может быть, стоит отказаться от кофе? Эти деньги можно потратить на что-то другое, в месяц выходит приличная сумма...",
      answers: [
        "А. Отказаться от маленьких трат. Экономия важна, но не должна превращаться в самоцель, которая не даёт тебе радость",
        "B. Следить за регулярными расходами и искать баланс (верно). Именно привычки и осознанный подход помогают достигать финансовых целей. Ищи баланс, а не пытайся отказаться от всего",
        "C. Кофе — это инвестиция в настроение. Трачу, сколько хочу, даже если это оверпрайс! Даже небольшие траты полезно учитывать и следить за ними"
      ],
      correctAnswer: 2,
    },
{
      id: "w4_bonus_referral_bonus",
      type: "bonus",
      activeColor: '#5E67E8',
      title: "Бонус за рекомендации",
      income: 500,
      cost: null,
      week: 4,
      name: "w4_bonus_referral_bonus",
      description: "По твоей рекомендации в команду вышел сильный специалист. В ВТБ ценят тех, кто помогает собирать классные команды"
    },
{
      id: "w4_minigame_financial_flow",
      type: "minigame",
      activeColor: '#479FFF',
      title: "Финансовый поток",
      incomes: [50, 300, 700],
      cost: null,
      week: 4,
      name: "w4_minigame_financial_flow",
      description: "Пересекай поток трат и рисков и доберись до финала"
    }
];