import gameoct1 from '../../../assets/images/lobby/game-oct1.webp';
import gameoct2 from '../../../assets/images/lobby/game-oct2.webp';
import gamerect from '../../../assets/images/lobby/gamerect.webp';
import investoct1 from '../../../assets/images/lobby/invest-oct1.webp';
import investoct2 from '../../../assets/images/lobby/invest-oct2.webp';
import investrect from '../../../assets/images/lobby/investrect.webp';
import quizoct1 from '../../../assets/images/lobby/quiz-oct1.webp';
import quizrect from '../../../assets/images/lobby/quizrect.webp';
import luckrect from '../../../assets/images/lobby/luckrect.webp';
import moneyrect from '../../../assets/images/lobby/moneyrect.webp';
import startTile from '../../../assets/images/lobby/startTile.webp';

export const CELL_WIDTH = 120;  // px
export const CELL_HEIGHT = 110; // px
export const START_CELL_WIDTH = 158;
export const START_CELL_HEIGHT = 126;
export const CHARACTER_WIDTH = 132;
export const CHARACTER_HEIGHT = 230;

export const MAX_MARGIN_LEFT = 170;   // чуть с запасом
export const MAX_MARGIN_TOP = 130;
export const MAX_CELL_W = START_CELL_WIDTH;
export const MAX_CELL_H = START_CELL_HEIGHT;

export const EXTRA_CELLS = 1;
/** Доп. ячейки вокруг вьюпорта, чтобы при быстром драге не мелькало */
export const CULL_BUFFER = 4;
/** Как часто пересчитывать видимые плитки во время драга (ms) */
export const VISIBLE_UPDATE_MS = 50;

export const MAX_X = 21;
export const MAX_Y = 8;

export const PAN_PADDING = {
  top: 120,
  right: 0,
  bottom: 200,
  left: 70,
};

//TODO: тексты просмотреть по фигме
export const GAME_CELLS = [
  {
    id: "start-1",
    x: 0,
    y: 38,
    tileSrc: startTile,
    cellType: 'start',
    activeColor: '#004CDA',
    width: START_CELL_WIDTH,
    height: START_CELL_HEIGHT,
    marginLeft: 0,
    marginTop: -25,
    shining: {
      marginLeft: -10,
      marginTop: 10,
    },
    separators: [
      {
        marginLeft: START_CELL_WIDTH - 22,
        marginTop: 10,
      },
      {
        marginLeft: START_CELL_WIDTH - 15,
        marginTop: START_CELL_HEIGHT - 70,
      },
    ],
  },
  {
    id: "w1_bonus_idea_award",
    x: 1,
    y: 38,
    tileSrc: moneyrect,
    marginLeft: 15,
    isRightSeparator: true,
    cellType: 'rect',
    type: "bonus",
    activeColor: '#5E67E8',
    week: 1,
    separators: [
      {
        marginLeft: 115,
        marginTop: 30,
      },
      {
        marginLeft: 125,
        marginTop: 65,
      },
    ],
  },
  {
    id: "w1_minigame_coin_runner",
    x: 2,
    y: 38,
    tileSrc: gameoct1,
    cellType: 'oct1',
    marginLeft: -5,
    isTopSeparator: true,
    marginTop: 5,
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [30, 120, 300],
    week: 1,
    separators: [
      {
        marginLeft: 23,
        marginTop: 10,
      },
      {
        marginLeft: 70,
        marginTop: 10,
      },
    ],
  },
  {
    id: "w1_luck_notification",
    x: 2,
    y: 37,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -20,
    marginTop: 45,
    isTopSeparator: true,
    type: "luck",
    activeColor: '#004CDA',
    week: 1,
    separators: [
      {
        marginLeft: -18,
        marginTop: 50,
      },
      {
        marginLeft: 52,
        marginTop: 50,
      },
    ],
  },
  {
    id: "w1_quiz_rich_or_broke",
    x: 2,
    y: 36,
    tileSrc: quizrect,
    cellType: 'rect',
    marginLeft: -50,
    marginTop: 80,
    separators: [
      {
        marginLeft: -48,
        marginTop: 84,
      },
      {
        marginLeft: 10,
        marginTop: 82,
      },
    ],
    type: "quiz",
    activeColor: '#479FFF',
    week: 1,
  },
  {
    id: "w1_investment_vtb_deposit",
    x: 2,
    y: 35,
    tileSrc: investoct1,
    cellType: 'oct1',
    marginLeft: -80,
    marginTop: 110,
    separators: [
      {
        marginLeft: 10,
        marginTop: 124,
      },
      {
        marginLeft: 33,
        marginTop: 160,
      },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_investment_financial_literacy_course",
    x: 3,
    y: 35,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -115,
    marginTop: 80,
    separators: [
      {
        marginLeft: -13,
        marginTop: 160,
      },
    ],
    commonMarginH: 10,
    type: "investment",
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_luck_fashion_shopping",
    x: 4,
    y: 35,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -140,
    marginTop: 90,
    separators: [
      {
        marginLeft: -137,
        marginTop: 95,
      },
      {
        marginLeft: -63,
        marginTop: 95,
      },
    ],
    type: "luck",
    activeColor: '#004CDA',
    week: 1,
  },
  {
    id: "w1_minigame_collect_capital",
    x: 4,
    y: 34,
    tileSrc: gameoct1,
    cellType: 'oct1',
    marginLeft: -160,
    marginTop: 120,
    separators: [
      {
        marginLeft: -80,
        marginTop: 125,
      },
      {
        marginLeft: -50,
        marginTop: 150,
      },
    ],
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [30, 120, 300],
    week: 1,
  },
  {
    id: "w1_bonus_initiative_bonus",
    x: 5,
    y: 34,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -210,
    marginTop: 75,
    separators: [
      { marginLeft: -210, marginTop: 85 },
      { marginLeft: -140, marginTop: 82 },
    ],
    type: "bonus",
    activeColor: '#5E67E8',
    week: 1,
  },
  {
    id: "w1_quiz_spare_money",
    x: 5,
    y: 33,
    tileSrc: quizrect,
    cellType: 'rect',
    marginLeft: -235,
    marginTop: 115,
    separators: [
      { marginLeft: -235, marginTop: 125 },
      { marginLeft: -185, marginTop: 115 },
    ],
    type: "quiz",
    activeColor: '#479FFF',
    week: 1,
  },
  {
    id: "w1_investment_scooter_subscription",
    x: 5,
    y: 32,
    tileSrc: investoct2,
    cellType: 'oct2',
    marginLeft: -280,
    marginTop: 145,
    type: "investment",
    zIndex: 6,
    separators: [
      { marginLeft: -275, marginTop: 155, zIndex: 5 },
      { marginLeft: -285, marginTop: 185, zIndex: 7 },
    ],
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_luck_autumn_season",
    x: 4,
    y: 32,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -265,
    marginTop: 105,
    type: "luck",
    separators: [
      { marginLeft: -260, marginTop: 110 },
      { marginLeft: -190, marginTop: 110 },
    ],
    activeColor: '#004CDA',
    week: 1,
  },
  {
    id: "w1_investment_vtb_shares",
    x: 4,
    y: 31,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -285,
    marginTop: 145,
    type: "investment",
    separators: [
      { marginLeft: -276, marginTop: 145 },
    ],
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_minigame_match3",
    x: 4,
    y: 30,
    tileSrc: gameoct1,
    cellType: 'oct1',
    marginLeft: -300,
    marginTop: 175,
    type: "minigame",
    separators: [
      { marginLeft: -220, marginTop: 180 },
      { marginLeft: -190, marginTop: 210 },
    ],
    activeColor: '#479FFF',
    incomes: [30, 120, 300],
    week: 1,
  },
  {
    id: "w1_bonus_vacation",
    x: 5,
    y: 30,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -345,
    marginTop: 135,
    type: "bonus",
    activeColor: '#5E67E8',
    separators: [
      { marginLeft: -250, marginTop: 160 },
      { marginLeft: -240, marginTop: 215 },
    ],
    week: 1,
  },
  {
    id: "w1_luck_bank_push",
    x: 6,
    y: 30,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -370,
    marginTop: 145,
    type: "luck",
    separators: [
      { marginLeft: -275, marginTop: 170 },
      { marginLeft: -265, marginTop: 225 },
    ],
    activeColor: '#004CDA',
    week: 1,
  },
  {
    id: "w1_investment_finance_conference_ticket",
    x: 7,
    y: 30,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -395,
    marginTop: 155,
    type: "investment",
    separators: [
      { marginLeft: -285, marginTop: 210, zIndex: 3 },
      { marginLeft: -295, marginTop: 240, zIndex: 6 },
    ],
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_quiz_70_discount",
    x: 8,
    y: 30,
    tileSrc: quizoct1,
    cellType: 'oct1',
    marginLeft: -410,
    marginTop: 200,
    type: "quiz",
    activeColor: '#479FFF',
    separators: [
      { marginLeft: -380, marginTop: 283, zIndex: 5, },
      { marginLeft: -320, marginTop: 280, zIndex: 5, },
    ],
    week: 1,
  },
  {
    id: "w1_investment_gym_membership",
    x: 8,
    y: 31,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -385,
    marginTop: 165,
    zIndex: 15,
    separators: [
      { marginLeft: -360, marginTop: 240, zIndex: 16, },
      { marginLeft: -290, marginTop: 240, zIndex: 16, },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_minigame_catch_items",
    x: 8,
    y: 32,
    zIndex: 17,
    tileSrc: gamerect,
    separators: [
      { marginLeft: -340, marginTop: 200, zIndex: 18, },
      { marginLeft: -270, marginTop: 200, zIndex: 18 },
    ],
    cellType: 'rect',
    marginLeft: -365,
    marginTop: 125,
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [30, 120, 300],
    week: 1,
  },
  {
    id: "w1_luck_past_returns",
    x: 8,
    y: 33,
    tileSrc: luckrect,
    zIndex: 18,
    cellType: 'rect',
    separators: [
      { marginLeft: -265, marginTop: 170, zIndex: 19 },
      { marginLeft: -240, marginTop: 160, zIndex: 19 },
    ],
    marginLeft: -345,
    marginTop: 85,
    type: "luck",
    activeColor: '#004CDA',
    week: 1,
  },
  {
    id: "w1_investment_bonds",
    x: 8,
    y: 34,
    tileSrc: investoct1,
    cellType: 'oct1',
    marginLeft: -285,
    marginTop: 60,
    zIndex: 19,
    separators: [
      { marginLeft: -185, marginTop: 135, zIndex: 20 },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_bonus_good_vibes",
    x: 9,
    y: 34,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -300,
    marginTop: 110,
    separators: [
      { marginLeft: -205, marginTop: 130 },
      { marginLeft: -195, marginTop: 175 },
    ],
    type: "bonus",
    activeColor: '#5E67E8',
    week: 1,
  },
  {
    id: "w1_investment_investing_book",
    x: 10,
    y: 34,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -325,
    marginTop: 115,
    type: "investment",
    separators: [
      { marginLeft: -238, marginTop: 130 },
      { marginLeft: -220, marginTop: 158 },
    ],
    activeColor: '#A171FF',
    week: 1,
  },
  {
    id: "w1_minigame_financial_flow",
    x: 11,
    y: 34,
    tileSrc: gameoct2,
    cellType: 'oct2',
    marginLeft: -353,
    marginTop: 95,
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [30, 120, 300],
    week: 1,
  },
  {
    id: "start-2",
    x: 11,
    y: 33,
    tileSrc: startTile,
    cellType: 'start',
    activeColor: '#004CDA',
    width: START_CELL_WIDTH,
    height: START_CELL_HEIGHT,
    marginTop: 50,
    marginLeft: -320,
    week: 2,
    lock: {
      marginTop: 0,
      marginLeft: -275,
    },
    separators: [
      { marginLeft: -296, marginTop: 45 },
    ],
  },
  {
    id: "w2_bonus_first_promotion",
    x: 11,
    y: 32,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -320,
    marginTop: 85,
    separators: [
      { marginLeft: -306, marginTop: 85 },
      { marginLeft: -250, marginTop: 90 },
    ],
    type: "bonus",
    activeColor: '#5E67E8',
    week: 2,
  },
  {
    id: "w2_minigame_coin_runner",
    x: 11,
    y: 31,
    tileSrc: gamerect,
    cellType: 'rect',
    marginLeft: -340,
    marginTop: 120,
    separators: [
      { marginLeft: -325, marginTop: 120 },
      { marginLeft: -270, marginTop: 125 },
    ],
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 150, 400],
    week: 2,
  },
  {
    id: "w2_luck_notification",
    x: 11,
    y: 30,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -360,
    marginTop: 155,
    separators: [
      { marginLeft: -345, marginTop: 155 },
      { marginLeft: -295, marginTop: 160 },
    ],
    type: "luck",
    activeColor: '#004CDA',
    week: 2,
  },
  {
    id: "w2_quiz_higher_stakes",
    x: 11,
    y: 29,
    tileSrc: quizoct1,
    cellType: 'oct1',
    marginLeft: -380,
    marginTop: 185,
    separators: [
      { marginLeft: -380, marginTop: 205 },
      { marginLeft: -385, marginTop: 225, zIndex: 12 },
    ],
    type: "quiz",
    activeColor: '#479FFF',
    week: 2,
  },
  {
    id: "w2_investment_carsharing_subscription",
    x: 10,
    y: 29,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -365,
    marginTop: 140,
    separators: [
      { marginLeft: -355, marginTop: 140 },
      { marginLeft: -295, marginTop: 145 },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_investment_negotiation_course",
    x: 10,
    y: 28,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -390,
    marginTop: 175,
    separators: [
      { marginLeft: -380, marginTop: 175 },
      { marginLeft: -320, marginTop: 180 },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_luck_delivery",
    x: 10,
    y: 27,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -410,
    marginTop: 210,
    separators: [
      { marginLeft: -400, marginTop: 210 },
      { marginLeft: -350, marginTop: 215 },
    ],
    type: "luck",
    activeColor: '#004CDA',
    week: 2,
  },
  {
    id: "w2_minigame_collect_capital",
    x: 10,
    y: 26,
    tileSrc: gameoct1,
    cellType: 'rect',
    marginLeft: -435,
    marginTop: 235,
    separators: [
      { marginLeft: -363, marginTop: 240 },
      { marginLeft: -335, marginTop: 265, },
    ],
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 150, 400],
    week: 2,
  },
  {
    id: "w2_bonus_quarterly_report_bonus",
    x: 11,
    y: 26,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -485,
    marginTop: 190,
    separators: [
      { marginLeft: -395, marginTop: 210 },
      { marginLeft: -385, marginTop: 270 },
    ],
    type: "bonus",
    activeColor: '#5E67E8',
    week: 2,
  },
  {
    id: "w2_quiz_vtb_call",
    x: 12,
    y: 26,
    tileSrc: quizrect,
    cellType: 'rect',
    marginLeft: -515,
    marginTop: 200,
    separators: [
      { marginLeft: -425, marginTop: 220 },
      { marginLeft: -415, marginTop: 280 },
    ],
    type: "quiz",
    activeColor: '#479FFF',
    week: 2,
  },
  {
    id: "w2_investment_mutual_fund",
    x: 13,
    y: 26,
    tileSrc: investrect,
    cellType: 'rect',
    marginLeft: -545,
    marginTop: 210,
    separators: [
      { marginLeft: -450, marginTop: 230, },
      { marginLeft: -445, marginTop: 290 },
    ],
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_luck_tax_deduction",
    type: "luck",
    x: 14,
    y: 26,
    tileSrc: luckrect,
    cellType: 'rect',
    marginLeft: -575,
    marginTop: 220,
    separators: [
      { marginLeft: -500, marginTop: 225 },
      { marginLeft: -550, marginTop: 220 },
    ],
    activeColor: '#004CDA',
    week: 2,
  },
  {
    id: "w2_investment_work_laptop",
    type: "investment",
    x: 14,
    y: 25,
    tileSrc: investoct1,
    cellType: 'oct1',
    marginLeft: -585,
    marginTop: 250,
    separators: [
      { marginLeft: -475, marginTop: 305, },
      { marginLeft: -485, marginTop: 275, },
    ],
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_minigame_match3",
    type: "minigame",
    x: 15,
    y: 25,
    tileSrc: gamerect,
    cellType: 'rect',
    marginLeft: -603,
    marginTop: 225,
    separators: [
      { marginLeft: -510, marginTop: 245, },
      { marginLeft: -500, marginTop: 305 },
    ],
    activeColor: '#479FFF',
    incomes: [50, 150, 400],
    week: 2,
  },
  {
    id: "w2_bonus_refer_a_friend",
    type: "bonus",
    x: 16,
    y: 25,
    tileSrc: moneyrect,
    cellType: 'rect',
    marginLeft: -630,
    marginTop: 230,
    separators: [
      { marginLeft: -550, marginTop: 235, },
    ],
    activeColor: '#5E67E8',
    week: 2,
  },
  {
    id: "w2_quiz_financial_habits",
    type: "quiz",
    activeColor: '#479FFF',
    week: 2,
  },
  {
    id: "w2_investment_vending_machine",
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_luck_airline_push",
    type: "luck",
    activeColor: '#004CDA',
    week: 2,
  },
  {
    id: "w2_investment_language_course",
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_minigame_catch_items",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 150, 400],
    week: 2,
  },
  {
    id: "w2_luck_currency_exchange",
    type: "luck",
    activeColor: '#004CDA',
    week: 2,
  },
  {
    id: "w2_quiz_salary_raise",
    type: "quiz",
    activeColor: '#479FFF',
    week: 2,
  },
  {
    id: "w2_investment_iis",
    type: "investment",
    activeColor: '#A171FF',
    week: 2,
  },
  {
    id: "w2_bonus_mentor_of_the_month",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 2,
  },
  {
    id: "w2_minigame_financial_flow",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 150, 400],
    week: 2,
  },
  {
    id: "w3_bonus_business_lounges",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 3,
  },
  {
    id: "w3_minigame_financial_flow",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 200, 550],
    week: 3,
  },
  {
    id: "w3_luck_email",
    type: "luck",
    activeColor: '#004CDA',
    week: 3,
  },
  {
    id: "w3_quiz_digital_financial_assets",
    type: "quiz",
    activeColor: '#479FFF',
    week: 3,
  },
  {
    id: "w3_investment_real_estate",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_investment_financial_resilience_book",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_luck_family_banking",
    type: "luck",
    activeColor: '#004CDA',
    week: 3,
  },
  {
    id: "w3_minigame_match3",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 200, 550],
    week: 3,
  },
  {
    id: "w3_bonus_free_consultation",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 3,
  },
  {
    id: "w3_quiz_corporate_client",
    type: "quiz",
    activeColor: '#479FFF',
    week: 3,
  },
  {
    id: "w3_investment_electric_car",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_luck_digital_ruble",
    type: "luck",
    activeColor: '#004CDA',
    week: 3,
  },
  {
    id: "w3_investment_floating_rate_deposit",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_minigame_collect_capital",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 200, 550],
    week: 3,
  },
  {
    id: "w3_investment_smartwatch",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_quiz_preferential_mortgage",
    type: "quiz",
    activeColor: '#479FFF',
    week: 3,
  },
  {
    id: "w3_bonus_refer_a_friend",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 3,
  },
  {
    id: "w3_luck_major_client",
    type: "luck",
    activeColor: '#004CDA',
    week: 3,
  },
  {
    id: "w3_investment_risk_management_workshop",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_minigame_catch_items",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 200, 550],
    week: 3,
  },
  {
    id: "w3_investment_investment_portfolio",
    type: "investment",
    activeColor: '#A171FF',
    week: 3,
  },
  {
    id: "w3_luck_property_tax",
    type: "luck",
    activeColor: '#004CDA',
    week: 3,
  },
  {
    id: "w3_quiz_loss_carryforward",
    type: "quiz",
    activeColor: '#479FFF',
    week: 3,
  },
  {
    id: "w3_bonus_delegate_routine",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 3,
  },
  {
    id: "w3_minigame_coin_runner",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 200, 550],
    week: 3,
  },
  {
    id: "w4_bonus_hybrid_schedule",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_minigame_coin_runner",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 300, 700],
    week: 4,
  },
  {
    id: "w4_luck_business_trip",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_quiz_american_race",
    type: "quiz",
    activeColor: '#479FFF',
    week: 4,
  },
  {
    id: "w4_investment_global_market_etf",
    type: "investment",
    activeColor: '#A171FF',
    week: 4,
  },
  {
    id: "w4_luck_office_cafe",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_bonus_corporate_psychologist",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_minigame_catch_items",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 300, 700],
    week: 4,
  },
  {
    id: "w4_luck_atm",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_quiz_high_investment_income",
    type: "quiz",
    activeColor: '#479FFF',
    week: 4,
  },
  {
    id: "w4_bonus_sports_community",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_luck_rent_payment_notification",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_investment_digital_assets",
    type: "investment",
    activeColor: '#A171FF',
    week: 4,
  },
  {
    id: "w4_minigame_collect_capital",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 300, 700],
    week: 4,
  },
  {
    id: "w4_investment_noise_canceling_headphones",
    type: "investment",
    activeColor: '#A171FF',
    week: 4,
  },
  {
    id: "w4_bonus_corporate_training",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_quiz_first_million",
    type: "quiz",
    activeColor: '#479FFF',
    week: 4,
  },
  {
    id: "w4_luck_cashback_surprise",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_bonus_extra_vacation_days",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_minigame_match3",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 300, 700],
    week: 4,
  },
  {
    id: "w4_luck_the_jacket",
    type: "luck",
    activeColor: '#004CDA',
    week: 4,
  },
  {
    id: "w4_investment_photo_booth",
    type: "investment",
    activeColor: '#A171FF',
    week: 4,
  },
  {
    id: "w4_quiz_matcha_with_coconut",
    type: "quiz",
    activeColor: '#479FFF',
    week: 4,
  },
  {
    id: "w4_bonus_referral_bonus",
    type: "bonus",
    activeColor: '#5E67E8',
    week: 4,
  },
  {
    id: "w4_minigame_financial_flow",
    type: "minigame",
    activeColor: '#479FFF',
    incomes: [50, 300, 700],
    week: 4,
  }
];
